### ISSUE TITLE
Trapdoors cause invisible blocks from a distance

### ISSUE THREAD

**Issue by SansIsTyping** [Modding-Legacy/Aether-Legacy#10]
This is with holystone bricks opposite the trapdoor, viewed from a distance. This may be a bug with other Aether Legacy blocks as well.
![https://i.imgur.com/RCMjuvi.png](https://i.imgur.com/RCMjuvi.png)
![https://i.imgur.com/hiwmocL.png](https://i.imgur.com/hiwmocL.png)

**Comment by 115kino** [comment]
What other mods were you using and can it be replicated with normal blocks?
