### ISSUE TITLE
 [1.11.2] Conflicting Inventory Slots

### ISSUE THREAD

**Issue by KIdWither** [Modding-Legacy/Aether-Legacy#100]
![2017-03-23_13 11 24](https://cloud.githubusercontent.com/assets/6080017/24260501/6bc516aa-0fca-11e7-82a0-06696683dcbd.png)
It would be nice to have a config option to have the extra inventory slots added in by Aether Legacy to have their own inventory tab, that way slots do not overlap with mods like baubles.

**Comment by 115kino** [comment]
Just like i've said in #103 I will not be changing the inventory override. The overlay issue is fixed in v1.4.1 (will release asap)
