### ISSUE TITLE
[1.10.2] Loss of F3 Debug Screen

### ISSUE THREAD

**Issue by Senseidragon** [Modding-Legacy/Aether-Legacy#102]
This bug is likely related to #96 and #101 .

Using a fresh minecraft 1.10.2 with latest forge version (2254 as of this report) and Aether Legacy v1.4 I get an extraneous Aether menu after creating a world.  I have verified that
`"aether menu options" {
    B:"Use Aether Menu"=false
}
`
is correctly set.
![1](https://cloud.githubusercontent.com/assets/1039223/24271104/4d535c94-0fee-11e7-823d-e7326c43d103.PNG)

Hitting ESC at this menu will make it go away and the world appears to function normally.  However the F3 debug screen is hidden.  Hitting F3 'appears' to do nothing...
![2](https://cloud.githubusercontent.com/assets/1039223/24271135/6b6e42a2-0fee-11e7-81dd-e6cf5cad555d.PNG)

but if you then hit ESC to get to the Minecraft menu, you can see the debug screen in the faded background.
![3](https://cloud.githubusercontent.com/assets/1039223/24271154/7ec5f5c0-0fee-11e7-9fb5-e5d03ce3fe03.PNG)

This is almost certainly not intended behavior.  :)

**Comment by 115kino** [comment]
Aether menu removed for v1.4.1 (will release asap)
