### ISSUE TITLE
[1.10.2] Request to use bauble

### ISSUE THREAD

**Issue by MysticAura** [Modding-Legacy/Aether-Legacy#103]
It would be incredibly helpful if you used bauble slots for your jewelry. It would make it far more compatible (and cleaner) in mod packs. If you really want your own slots, then possibly add a tab. As it is it's very cluttered and crowded.

**Comment by 115kino** [comment]
I'm sorry but this has been requested for a while and i've already stated that I will not be changing the inventory screen.
