### ISSUE TITLE
[1.11.2][v1.4][Bug]A Few Crashes

### ISSUE THREAD

**Issue by Leafygreens97** [Modding-Legacy/Aether-Legacy#106]
Whenever I right click to open the GUI for either of these blocks, it crashes the game. I don't know if they will help, but I've provided a crash report for each instance of me attempting to open an Incubator and a Freezer:
[incubatorcrashreport.txt](https://github.com/Modding-Legacy/Aether-Legacy/files/869800/incubatorcrashreport.txt)
[freezercrashreport.txt](https://github.com/Modding-Legacy/Aether-Legacy/files/869801/freezercrashreport.txt)

UPDATE: Oh dear, I was posting logs, not crashes. Fixed that. The game also crashes when attempting to right click a Phygg and a Flying Cow with a saddle. I couldn't test it with Moas since I'm not able to raise one. I've also tested all of these scenarios in the latest version of Aether Legacy for 1.10.2, which worked just fine. So I don't think its an issue with my computer(or maybe it is). Also, I renamed these crash reports just to make it a bit easier for you. Sorry if that's suspicious. Here are the Phygg and Cow ones:
[phyggcrashreport.txt](https://github.com/Modding-Legacy/Aether-Legacy/files/869802/phyggcrashreport.txt)
[cowcrashreport.txt](https://github.com/Modding-Legacy/Aether-Legacy/files/869803/cowcrashreport.txt)

**Comment by 115kino** [comment]
To be blunt, I was setting ItemStacks as null instead of empty, Fixed in v1.4.1 (will release asap)
