### ISSUE TITLE
Crash in server environment

### ISSUE THREAD

**Issue by DeGariless** [Modding-Legacy/Aether-Legacy#107]
Tested with nothing but forge and Aether. Server will not start up.
Aether: aether_legacy-1.10.2-1.4
Forge: 2254

[crash-2017-03-24_20.49.25-server.txt](https://github.com/Modding-Legacy/Aether-Legacy/files/869649/crash-2017-03-24_20.49.25-server.txt)

**Comment by JoelZBub** [comment]
Please check the closed issues. This is a duplicate of #98 which has been closed.

**Comment by 115kino** [comment]
Just as @JoelZBub said, this is fixed.
