### ISSUE TITLE
[1.11.2+1.10.2] Sheepuffs have 20 health

### ISSUE THREAD

**Issue by TheCorruption** [Modding-Legacy/Aether-Legacy#109]
This is more than every other animal in the Aether, the health should be lowered to 10 or 8.

**Comment by brodycas3** [comment]
Don't normal sheep have 4?

**Comment by KingPhygieBoo** [comment]
Nope, 8.

**Comment by 115kino** [comment]
Fixed in v1.4.1 (will release asap)
