### ISSUE TITLE
Portal issue

### ISSUE THREAD

**Issue by brodycas3** [Modding-Legacy/Aether-Legacy#11]
When entering an already loaded aether it lags a bit not letting me leave the portal right away and teleports you back as seen in this video.

https://u.nya.is/fsmyxp.mp4

**Comment by SansIsTyping** [comment]
This is because when you are still loading clientside (because shaders), the serverside is still running and it sees you inside the portal. The issue here is that if you are still in the portal after you go into or out of the Aether, it will keep teleporting you until you leave the portal.

**Comment by 115kino** [comment]
Can you please try replicating the issue with just Aether Legacy?

**Comment by brodycas3** [comment]
Why do you think that i have aether II installed?

**Comment by 115kino** [comment]
What? Please explain.

**Comment by brodycas3** [comment]
Oh I read that wrong. Sure let me get right on it.

**Comment by brodycas3** [comment]
It doesn't do it. BTW here are the mods that I had enabled. The checkmark one's fo course.

http://i.imgur.com/5YPEHtM.png

**Comment by 115kino** [comment]
Judging by the video it's most likely caused by the shaders. You can re-open/recreate this issue if it does happen without shaders.

**Comment by brodycas3** [comment]
It does it without shaders.

**Comment by brodycas3** [comment]
I can't reopen the issue because you closed it.
