### ISSUE TITLE
[1.11.2] Inventory Issues with other mods

### ISSUE THREAD

**Issue by xLastt** [Modding-Legacy/Aether-Legacy#112]
Uhmm, Aether adds a new inventory interface but have collision with other mods buttons and make the inventory interface so ugly x.x!

Ex: Baubles, CosmeticAmor, Quark/Chest Inventory Buttons

Sorry for the bad english.

**Comment by 115kino** [comment]
So after weeks of thinking, i'm just going to implement I button for the inventory. It's going to be for v1.4.1 and future versions above it.
