### ISSUE TITLE
Tinkers' Construct picks don't work on the slider

### ISSUE THREAD

**Issue by SilverDavidMC** [Modding-Legacy/Aether-Legacy#113]
I realize this isn't necessarily a bug, but I feel that it should be there for consistency. The pickaxe is named "tconstruct:pickaxe" in the code, and the hammer is "tconstruct:hammer" if you decide to do that too since it also works on mining stone.

**Comment by Spearkiller** [comment]
From what i've found, the only pickaxes that work on the slider are Vanilla ones, Aether ones (obviously), and Project Red ones.

**Comment by 115kino** [comment]
Added into 1.11.2 and 1.9.4. (1.10.2 will have this patch on a later date)
