### ISSUE TITLE
[MC 1.11.2] [v1.4] Opening freezer and incubator GUI crashes the game

### ISSUE THREAD

**Issue by dmushcow** [Modding-Legacy/Aether-Legacy#115]
I was playing with the mod installed, exploring the dimension till I found the Silver Dungeon. Looting the chests I found a moa's egg, so I decided to use the incubator, but when I right clicked it, the game crashed. The same happened with the freezer; I hope this will be fixed soon due I love the mod and the work you have done is awesome. Keep it up!
Also, there is the list of the mods that I installed alongside Aether Legacy v1.4:

AutoRegLib 1.1-4
BabyAnimals 1.11
Giacomo's Foundry 1.3.12
Hopper Ducts 1.4.9
Infernal Mobs 1.11.2
JEI 4.2.10.248
Optifine HD U B7
Quark 1.2-90
TreeChopper 1.1.2
Waystones 3.0.13
Roots 2 0.014

**Comment by 115kino** [comment]
Fixed for 1.11.2 release
