### ISSUE TITLE
Conflict With The Aether II's Portal

### ISSUE THREAD

**Issue by JohnArmy** [Modding-Legacy/Aether-Legacy#119]
This is probably pretty obvious but I just want to make it apparent. I've been messing around with The Aether II and Aether Legacy and I couldn't go to the 2nd Aether Dimension. It always made the Aether Legacy portal no matter where I placed the water. The only fix I found for survival play is to make a recipe for the Aether II's "Aether Portal Frame" which spawns the portal. The creation of a recipe is fine with me but I doubt that everyone would feel the same. The only fix I can think of is by making the portal spawn in the frame only on a certain block or something like that. I hope I helped bring out the issue. Thanks for reading ;)

**Comment by Vazkii** [comment]
...why would you have both?

**Comment by JohnArmy** [comment]
I want both nostalgia and new innovations. That's why

**Comment by JohnArmy** [comment]
And

**Comment by peterix** [comment]
It would be funny if they stacked. Fall from the new one? You fall through the old one!

**Comment by JohnArmy** [comment]
Lol that's actually a very cool idea! But probably too complicated to program :\ and also a bit unnecessary. But still, very cool :D

**Comment by brodycas3** [comment]
Well I'm sure the creation of aether legacy is full of complicated code.

**Comment by Indianajaune** [comment]
I think using the 2 versions of the mod at the same time is a very weird idea. It's like wanting to play assassin's creed 2 in assassin's creed 3, the game deigns are conflicting, not speaking about the lore story.

**Comment by 115kino** [comment]
It's been talked about multiple times, one idea would be using continuum as a means of travel but besides that no other ideas have made sense. (any ideas would be nice)

**Comment by KingPhygieBoo** [comment]
Continuum was removed from Aether II.

**Comment by Indianajaune** [comment]
Or maybe a divine artifact with time travelling properties?

**Comment by jredfox** [comment]
Just phycially make a new bucket called wooden bucket to make the portal if Loader.isModLoaded("aetherii");

**Comment by KingPhygieBoo** [comment]
No new content is going to be added.

**Comment by brodycas3** [comment]
I have an idea. Right click the portal to select which dimension you want
it to teleport you to.

**Comment by jredfox** [comment]
Seems Like It would break my addon or other people's addons for the aether It should just be a wooden bucket or another bucket to get to the aether one if the aether ii is loaded

**Comment by KingPhygieBoo** [comment]
You could just add something to access each dimension in the addon. Or you could use the Skyroot Buckets from each mod. But no new items are going to be added to Aether Legacy, expecially if they weren't planned for/in the original.

**Comment by jredfox** [comment]
I tried the skyroot bucket from the aether legacy it didn't work

**Comment by KingPhygieBoo** [comment]
It does work, I have tested it.

**Comment by jredfox** [comment]
Also it shouldn't have to be an addon to fix the aether legacy compatibility

**Comment by jredfox** [comment]
Ok that works but, it needs a regular bucket someone could be able to access via the overworld

**Comment by KingPhygieBoo** [comment]
I know this issue was discussed in the past, but I don't think it's ever planned to be fixed, it would be pointless to have both Aether dimensions, very confusing too.

**Comment by KingPhygieBoo** [comment]
I just discussed Aether II compatibility with Kino, this is not planned to be added.
