### ISSUE TITLE
Aether Legacy v1.4.1 crashing with Creative+ mode of NEI

### ISSUE THREAD

**Issue by proEndreeper** [Modding-Legacy/Aether-Legacy#123]
Crash Report: https://www.pastiebin.com/5917355e679ed

Details leading up to problem:
1. Create a new world in creative mode.
2. Open NEI and go into Creative+ mode
3. Exit out of inventory
4. Reopen inventory
5. Crash.

**Comment by 115kino** [comment]
v1.4.1 hasn't released yet unless you're talking about the recent builds. The inventory button and its code has been changed. The issue should no longer occur in 1.4.1 and 1.0.1 when they release.
