### ISSUE TITLE
[1.11.2][1.0] Treasure Chest Throws errors in Wawla and One Probe

### ISSUE THREAD

**Issue by unwarymold9171** [Modding-Legacy/Aether-Legacy#124]
Whenever looking at the Treasure Chest with Wawla it puts a "This block did a bad. Check console." (I could not find the console it referred to), One prob crashes because of no catch statement on the isValid() method.  This leads me to believe that there is an issue with how the tile entity is made.

For recreating this error, I had opened the trap doors that appear after defeating the silver dungeon.

**Comment by 115kino** [comment]
The fix has been added in 1.10.2 and will be added to future versions real soon.
