### ISSUE TITLE
Crash when looking at the Bronze Dungeon Chest

### ISSUE THREAD

**Issue by Konclan** [Modding-Legacy/Aether-Legacy#126]
On the version v1.0 (v1.4.1) for Minecraft 1.11.2, I crash whenever I look directly at a bronze dungeon chest. This is an issue with The One Probe, after disabling the visibility of The one probe the crash doesn't occure. I still suggest taking a look.

Here is the full crash report: https://pastebin.com/auvq06ay

**Comment by 115kino** [comment]
The fix has been added in 1.10.2 and will be added to future versions real soon.
