### ISSUE TITLE
Crash when using Hammer of Notch

### ISSUE THREAD

**Issue by Vazkii** [Modding-Legacy/Aether-Legacy#127]
Got a game crash when using the Hammer of Notch. I used it a few times before and it didn't happen, though. The item was freshly pulled from the creative menu.

https://gist.github.com/Vazkii/fb87fc962223e5277f6aecd8f45891c0#file-gistfile1-txt-L1311

**Comment by 115kino** [comment]
Fix uploaded to github and will be applied to 1.4.1 and other future versions.
