### ISSUE TITLE
Neverending portal Loop

### ISSUE THREAD

**Issue by Draconus80** [Modding-Legacy/Aether-Legacy#128]
I downloaded the mod from here: http://www.mc-mod.net/aether-legacy-mod/  for Minecraft 1.11.2 and it worked fine till I went through the portal a second or third time, where I got stuck in a never ending teleportation loop that could only be escaped by either leaving the game or having an opped player use the tp command to "yank" me out of the portal

**Comment by 115kino** [comment]
tested with the recent changes. This should no longer occur with v1.4.1 and onward when released.
