### ISSUE TITLE
Crashing when launching a world

### ISSUE THREAD

**Issue by Ryan2904** [Modding-Legacy/Aether-Legacy#131]
I have the mod installed correctly (have to use a cracked TLauncher as my original cracked Minecraft didn't work properly) which should work fine as it's entirely clean. But whenever I try to load into a world with the mod installed, my game doesn't respond then crashes. Is there a known issue and fix for this? If so, do tell.

**Comment by 115kino** [comment]
(Can't really help you if that client is cracked) Please try and provide a crash report.
