### ISSUE TITLE
[Suggestion] New Inventory GUI Layout

### ISSUE THREAD

**Issue by InsomniaKitten** [Modding-Legacy/Aether-Legacy#134]
**I decided to create some new designs as I really don't like the layout of the crafting grid in the current GUI design. If you see any problems with these designs, please let me know.**

---
With a similar philosophy to the Baubles GUI, this design maintains the position of the player render and open/close button across GUIs, making it easier on the player to quickly open and close the inventory in order to glance at the slots, without needing to move the cursor. It also shifts the crafting grid to a horizontal layout, allowing for a localized label, to maintain consistency with the vanilla inventory

![](http://i.imgur.com/ieS2T0W.png)

Similar to the first mockup, although this keeps to the original layout, with the exception of the crafting grid, which, once again, is shifted to a horizontal layout, with space for a localized label.

![](http://i.imgur.com/IzCSVMP.png)

Alternatively, a design with the players render being the center-focus of the GUI. Similar design for the crafting grid, again, to maintain consistency. The width of the box for the player render is one pixel smaller in this variant; 50px wide down from 51px.

![](http://i.imgur.com/cxvmDa6.png)

**Comment by 115kino** [comment]
Thank you @InsomniaKitten for the great new inventory textures. You will be credited for your work.
