### ISSUE TITLE
Ticking entity crash

### ISSUE THREAD

**Issue by RocketLazer** [Modding-Legacy/Aether-Legacy#135]
My Minecraft will have a Ticking entity crash when I'm fighting the Slider, the Sun Spirit and even slimes.

I have many mods in my Minecraft so its hard to tell what mods conflict with each other. 

Here is the Crash log: [crash-2017-06-06_09.45.08-server.txt](https://github.com/Modding-Legacy/Aether-Legacy/files/1053630/crash-2017-06-06_09.45.08-server.txt)

Thx in Advance,

**Comment by 115kino** [comment]
Seems to be an issue with TheXFactor117's Level mod. I'll go and make a report about it on their issue tracker.
