### ISSUE TITLE
"What is this block" mods show chest mimics

### ISSUE THREAD

**Issue by Claycorp** [Modding-Legacy/Aether-Legacy#139]
This kinda makes them pointless as you can see what is a chest and what isn't.

**Comment by Lachney** [comment]
You aren't supposed to know what they are if you don't use external mods & plugins with Aether Legacy. We could always rename him in the language file that they are just normal chests but its name like "aether_legacy:chest_mimic" would most likely still give it away. Anyway, something we cannot fix but if you want to be surprised, I recommend not using "What is this block". HehehehehehHHAhaha!
