### ISSUE TITLE
Sponge Server 1.11.2 Not allowing users to access the Aether inventory

### ISSUE THREAD

**Issue by chubbymomo** [Modding-Legacy/Aether-Legacy#140]
So the users of my 1.11.2 Sponge server, crash every time they press the gray button to access the Aether inventory. Note: The users crash not the server itself.

**Comment by Leafygreens97** [comment]
I think this is more of an issue with Sponge than it is with Aether Legacy, as the inventory works just fine without Sponge installed. I already posted an issue about this on the Sponge page.

**Comment by chubbymomo** [comment]
So are there any Sponge alternatives?

**Comment by 115kino** [comment]
Can you please provide a crash report? I'll see what I can do once I can pin-point where the issue is happening.

**Comment by 115kino** [comment]
Tested with recent builds and this issue seems to not occur at all even if the server has Aether Legacy installed or not. If somehow this issue does occur in 1.4.1 and 1.0.1 please make a new issue with a crash report that the clients receive.
