### ISSUE TITLE
(1.11) Many problems with mobs

### ISSUE THREAD

**Issue by TheCorruption** [Modding-Legacy/Aether-Legacy#141]
- Moas flap way more slowly than aether I.
- Moas, cockatrices, phygs, and flying cows flap their wings when near a ledge.
- Flying cows can't be milked with a skyroot bucket.
- regular Sheepuffs have the puffed model, and can't be sheared at all.
- Aerbunnies jump instead of hop, are always jumping, and dont sweat or run when attacked.
- Aerwhales have the wrong texture and dont fly into the air when attacked.
- Swets have no animation and dont sweat.
- Sentries have a weaker explosion and the model has Z-fighting when lit.
- Zephyrs always stare directly at the player unlike Aether I.
- Aechor Plants don't speed up their animation when the player is close.
- Mimics always run, even when standing still.
- Aechor plants and cockatrices fire darts instead of needles, and mobs who are attacked by them don't bleed.

**Comment by KingPhygieBoo** [comment]
The Sheepuff keep the puffed model after they eat grass, until you shear them. The Aerwhale's texture is correct, or at least was made to be correct. The Moa flapping is the exact same from what I've seen, and pretty sure it uses very similar code. The Aechor plants speeding up is an Aether II thing I believe.

**Comment by TheCorruption** [comment]
These were all compared to pre-release 2 since I can't find a newer version, but from what I tested, the aerwhale in aether I doesn't have gold markings, and the sheepuff has the same model no matter what state it is in when playing Aether Legacy, you can only tell if its puffed by how fast they fall.

**Comment by KingPhygieBoo** [comment]
The Aerwhale had a different model alltogether, with the gold markings, in 1.7b. And with the Sheepuff, are you saying it always has the default or puffed model?

**Comment by TheCorruption** [comment]
The sheepuff always has the puffed model, I know its supposed to have the default model because it falls at a normal speed.

**Comment by KingPhygieBoo** [comment]
When it eats grass, it should go into the air, and come down, keeping the puffed model until sheared, then it goes to default, then sheared. That's what I think it's supposed to be like.
