### ISSUE TITLE
game crashes when I try to saddle a sky pig or sky cow/ HUD, hand, held items, and  block highlighter not present when save is loaded manually/etc.

### ISSUE THREAD

**Issue by skadooshbag** [Modding-Legacy/Aether-Legacy#144]
several issues to report.

1) when I load the save manually (that is, by going into single player and selecting the world, as opposed to using quickload), the quickbar hud is missing (it shows up when I go into my inventory or interact with something like a furnace or crafting table, but disappears again as soon as I exit).  also missing is the Crosshair recticule, the black outline that highlights whichever block I'm looking at, and (in first person) my hand and the currently held item. loading via quickload does not pose any of these issues.

2) when I try to put a saddle on a sky pig or sky cow, the game freezes and then crashes (regardless of what means by which I load my game). I then get this message: 

"_The game crashed whilst unexpected error
Error: java.lang.NullPointerException: The validated object is null_"

clicking the "view crash report" button does nothing. saddling an ordinary overworld pig works fine (have yet to try a horse)

3) when I jump off a ledge and back into the overworld,  I land, walk a few blocks, and _then_ die from fall damage. I would dismiss this as my computer being slow, but it occured even when I used the parachute. (it was the gold parachute given to me upon first entering the aether, and it was literally the last use the parachute had left in it, as it broke immediately, despite my descent still slowing).

4)relatedly, the crafting recipes for parachutes do not seem to work (I've been working under the assumption that it consists of a single row of three identical cloud blocks, as that is the recipe that the wiki gave me)

5-6)I am also experiencing the allegedly-solved "lore book displays overlapping text when empty" and "overworld music plays on top of aether music" glitches.

7)moas will flap their wings, but not move anywhere or even lift off the ground at all. their only valid method of locomotion is walking.

If it helps, I am playing the 1.11.2 version of minecraft and using the 1.4 version of the aether legacy mod. I am using the 1.10.2-6.3.2 version of the ichun-util jar file.  the other mods I am using are the Better Bedrock Generation Mod, the Better Survival Mod, the Death Bags Mod, the Environmental Creepers Mod, the Mo' Villages Mod, and the Lucky Block Mod.

**Comment by skadooshbag** [comment]
Oh, and the sky sheep are unshearable and randomly shoot up into the air and temporarily levitate sometimes when one of those ghast-things that shoots knockback snowballs is attacking me.

**Comment by skadooshbag** [comment]
Oh, and I'm currently inside what appears to be a dungeon (don't know how to identify the kind). I did not however start a party or anything, I simply broke through wihtout the blocks reappearing immediatey (although I think that's for the sequel mod).  four out of five chests simply dissapear when I try to open them, and don't drop anything (even themselves) when I break them. also, I keep hearing a random clickign noise as I walk, as though I stepped on a pressure plate, although I cannot identify the source.

**Comment by 115kino** [comment]
for the first issue, can you send a picture of this happening? For the second issue, can you please send the crash-log for when this happens? And about the last comment, this is due to the fact you are most likely on peaceful mode. Hostile mobs are trying to spawn however due to peaceful mode being active they will not spawn.

**Comment by skadooshbag** [comment]
OH, an now that I found out about the white antipoison apples, I ate one after getting shot at by one of those annoying plant things, and now my screen keeps flashing green, and it doesn't stop for quite a few seconds.

@115kino 

ah, those chest spawn hostiles. got it. thanks.

I don't know how to access the crash log.  if I have to click on the "veiw crash report" button, then YOu're outta luck for reasons already explained.

However, while looking for the screenshots folder, I found the crash reports folder.  here is the most recent one: 

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 6/23/17 6:49 PM
Description: Unexpected error

java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
	at net.minecraft.util.NonNullList.set(SourceFile:45)
	at net.minecraft.entity.player.InventoryPlayer.func_70299_a(InventoryPlayer.java:513)
	at com.legacy.aether.common.entities.util.EntitySaddleMount.func_184645_a(EntitySaddleMount.java:96)
	at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1213)
	at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1190)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187097_a(PlayerControllerMP.java:533)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1509)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1744)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
	at net.minecraft.util.NonNullList.set(SourceFile:45)
	at net.minecraft.entity.player.InventoryPlayer.func_70299_a(InventoryPlayer.java:513)
	at com.legacy.aether.common.entities.util.EntitySaddleMount.func_184645_a(EntitySaddleMount.java:96)
	at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1213)
	at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1190)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187097_a(PlayerControllerMP.java:533)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1509)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Player'/227, l='MpServer', x=-479.05, y=82.00, z=655.92]]
	Chunk stats: MultiplayerChunkCache: 1194, 1194
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-256,64,192), Chunk: (at 0,4,0 in -16,12; contains blocks -256,0,192 to -241,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2606002 game time, 3394522 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 103 total; [EntityFlyingCow['Flying Cow'/7682, l='MpServer', x=-558.50, y=64.00, z=618.50], EntitySheepuff['Sheepuff'/9219, l='MpServer', x=-509.39, y=82.00, z=637.99], EntitySheepuff['Sheepuff'/9220, l='MpServer', x=-513.46, y=81.00, z=646.32], EntitySheepuff['Sheepuff'/9221, l='MpServer', x=-507.54, y=82.00, z=638.29], EntitySheepuff['Sheepuff'/7685, l='MpServer', x=-551.51, y=68.00, z=622.27], EntitySheepuff['Sheepuff'/9222, l='MpServer', x=-512.66, y=82.00, z=644.12], EntitySheepuff['Sheepuff'/7686, l='MpServer', x=-544.59, y=71.00, z=610.74], EntityPhyg['Phyg'/9223, l='MpServer', x=-489.41, y=80.00, z=650.26], EntitySheepuff['Sheepuff'/7687, l='MpServer', x=-548.50, y=74.00, z=618.50], EntityPhyg['Phyg'/9224, l='MpServer', x=-455.50, y=86.00, z=659.60], EntitySheepuff['Sheepuff'/7688, l='MpServer', x=-549.50, y=73.00, z=618.45], EntityPhyg['Phyg'/9225, l='MpServer', x=-477.37, y=82.00, z=655.50], EntitySheepuff['Sheepuff'/7689, l='MpServer', x=-544.77, y=75.00, z=616.52], EntityPhyg['Phyg'/9226, l='MpServer', x=-463.45, y=86.00, z=650.50], EntitySheepuff['Sheepuff'/7690, l='MpServer', x=-541.45, y=78.00, z=631.76], EntitySheepuff['Sheepuff'/7691, l='MpServer', x=-546.63, y=75.00, z=618.35], EntityPhyg['Phyg'/9227, l='MpServer', x=-461.66, y=85.00, z=654.50], EntityPhyg['Phyg'/9228, l='MpServer', x=-465.50, y=85.00, z=651.45], EntitySheepuff['Sheepuff'/7692, l='MpServer', x=-542.50, y=76.00, z=616.50], EntityFlyingCow['Flying Cow'/9229, l='MpServer', x=-448.88, y=87.00, z=643.48], EntityMoa['Moa'/9230, l='MpServer', x=-461.22, y=86.00, z=646.92], EntityMoa['Moa'/9231, l='MpServer', x=-434.18, y=86.00, z=643.83], EntityFlyingCow['Flying Cow'/9232, l='MpServer', x=-438.85, y=88.00, z=650.82], EntityPhyg['Phyg'/9233, l='MpServer', x=-439.35, y=88.00, z=655.50], EntityFlyingCow['Flying Cow'/9234, l='MpServer', x=-447.23, y=90.00, z=648.48], EntityPhyg['Phyg'/9235, l='MpServer', x=-433.43, y=85.00, z=641.71], EntityPhyg['Phyg'/9236, l='MpServer', x=-433.50, y=84.00, z=636.75], EntityPhyg['Phyg'/9237, l='MpServer', x=-418.83, y=83.00, z=652.43], EntityFlyingCow['Flying Cow'/9238, l='MpServer', x=-427.49, y=86.00, z=656.32], EntityFlyingCow['Flying Cow'/9256, l='MpServer', x=-435.78, y=88.00, z=665.90], EntityPhyg['Phyg'/9257, l='MpServer', x=-436.81, y=88.00, z=664.90], EntityMoa['Moa'/9258, l='MpServer', x=-435.31, y=88.00, z=661.09], EntityPhyg['Phyg'/9259, l='MpServer', x=-434.03, y=87.00, z=668.76], EntityAerbunny['Aerbunny'/9260, l='MpServer', x=-416.10, y=83.68, z=668.51], EntityPhyg['Phyg'/9261, l='MpServer', x=-440.88, y=87.00, z=667.82], EntityMoa['Moa'/9262, l='MpServer', x=-445.22, y=90.00, z=664.93], EntityPhyg['Phyg'/9263, l='MpServer', x=-416.50, y=83.00, z=663.35], EntityMoa['Moa'/9264, l='MpServer', x=-425.12, y=86.00, z=662.11], EntityPhyg['Phyg'/9284, l='MpServer', x=-464.69, y=80.00, z=684.54], EntityPhyg['Phyg'/9286, l='MpServer', x=-460.25, y=83.00, z=683.59], EntityPhyg['Phyg'/9290, l='MpServer', x=-432.93, y=87.00, z=679.55], EntityMoa['Moa'/9291, l='MpServer', x=-442.04, y=87.00, z=675.74], EntityPhyg['Phyg'/9292, l='MpServer', x=-429.70, y=86.00, z=687.86], EntityPhyg['Phyg'/9293, l='MpServer', x=-427.41, y=85.00, z=680.72], EntityAerbunny['Aerbunny'/9312, l='MpServer', x=-461.94, y=81.28, z=687.51], EntityAerbunny['Aerbunny'/9313, l='MpServer', x=-475.07, y=77.28, z=693.50], EntityAerbunny['Aerbunny'/9314, l='MpServer', x=-460.62, y=82.00, z=686.35], EntityPhyg['Phyg'/9315, l='MpServer', x=-464.36, y=80.00, z=688.27], EntityPhyg['Phyg'/9316, l='MpServer', x=-465.29, y=80.00, z=688.17], EntityAerbunny['Aerbunny'/9317, l='MpServer', x=-464.21, y=81.17, z=689.63], EntityAerbunny['Aerbunny'/9318, l='MpServer', x=-445.14, y=87.75, z=678.74], EntityAerbunny['Aerbunny'/9319, l='MpServer', x=-451.37, y=85.48, z=673.20], EntityFlyingCow['Flying Cow'/9320, l='MpServer', x=-442.50, y=81.00, z=702.50], EntityPhyg['Phyg'/9321, l='MpServer', x=-428.39, y=84.00, z=690.71], EntityAerbunny['Aerbunny'/9322, l='MpServer', x=-428.96, y=86.00, z=689.04], EntityPhyg['Phyg'/9324, l='MpServer', x=-413.29, y=80.00, z=695.77], EntityAerbunny['Aerbunny'/7340, l='MpServer', x=-428.28, y=80.18, z=614.38], EntityMoa['Moa'/7341, l='MpServer', x=-429.55, y=76.00, z=602.47], EntityMoa['Moa'/7342, l='MpServer', x=-422.79, y=82.00, z=604.94], EntityMoa['Moa'/7343, l='MpServer', x=-425.33, y=82.00, z=639.60], EntityMoa['Moa'/7368, l='MpServer', x=-443.48, y=80.00, z=615.66], EntityMoa['Moa'/7369, l='MpServer', x=-430.36, y=85.00, z=643.44], EntityFlyingCow['Flying Cow'/7370, l='MpServer', x=-447.47, y=86.00, z=635.78], EntityAerbunny['Aerbunny'/7371, l='MpServer', x=-450.12, y=86.18, z=630.46], EntitySwet['Swet'/10443, l='MpServer', x=-413.81, y=79.00, z=636.37], EntityAechorPlant['Aechor Plant'/10452, l='MpServer', x=-519.50, y=45.00, z=590.50], EntityPlayerSP['Player'/227, l='MpServer', x=-479.05, y=82.00, z=655.92], EntitySlider['Slider'/6411, l='MpServer', x=-412.00, y=42.00, z=614.00], EntityFlyingCow['Flying Cow'/7439, l='MpServer', x=-456.77, y=49.00, z=577.50], EntityMoa['Moa'/7440, l='MpServer', x=-463.86, y=67.00, z=603.88], EntityMoa['Moa'/7441, l='MpServer', x=-447.04, y=80.00, z=615.82], EntityMoa['Moa'/7442, l='MpServer', x=-443.82, y=83.00, z=622.61], EntityMoa['Moa'/7443, l='MpServer', x=-466.03, y=83.00, z=638.52], EntityFlyingCow['Flying Cow'/7444, l='MpServer', x=-470.45, y=82.00, z=639.55], EntityFlyingCow['Flying Cow'/7445, l='MpServer', x=-449.62, y=86.00, z=637.00], EntityAerbunny['Aerbunny'/7446, l='MpServer', x=-456.80, y=84.00, z=631.08], EntitySwet['Swet'/10520, l='MpServer', x=-524.86, y=75.00, z=617.40], EntityAechorPlant['Aechor Plant'/10010, l='MpServer', x=-553.50, y=67.00, z=636.50], EntityAechorPlant['Aechor Plant'/10548, l='MpServer', x=-550.50, y=76.00, z=625.50], EntityAerbunny['Aerbunny'/7478, l='MpServer', x=-479.75, y=45.25, z=591.32], EntityAerbunny['Aerbunny'/7479, l='MpServer', x=-476.95, y=42.08, z=579.67], EntityPhyg['Phyg'/7480, l='MpServer', x=-479.34, y=76.00, z=622.53], EntityItem['item.tile.lightgem'/10552, l='MpServer', x=-463.71, y=83.00, z=664.07], EntityPhyg['Phyg'/7482, l='MpServer', x=-474.99, y=82.00, z=646.87], EntityAerbunny['Aerbunny'/7526, l='MpServer', x=-478.68, y=42.08, z=586.48], EntityAerbunny['Aerbunny'/7527, l='MpServer', x=-475.69, y=42.38, z=576.24], EntityItem['item.tile.lightgem'/10637, l='MpServer', x=-430.13, y=75.00, z=602.59], EntityFlyingCow['Flying Cow'/9616, l='MpServer', x=-446.45, y=79.00, z=709.55], EntityFlyingCow['Flying Cow'/9617, l='MpServer', x=-445.50, y=81.00, z=704.50], EntityFlyingCow['Flying Cow'/9618, l='MpServer', x=-446.50, y=80.00, z=705.50], EntityAerbunny['Aerbunny'/9620, l='MpServer', x=-434.95, y=86.18, z=694.60], EntityMoa['Moa'/9621, l='MpServer', x=-417.79, y=80.00, z=704.80], EntityMoa['Moa'/9622, l='MpServer', x=-415.50, y=79.00, z=708.50], EntityPhyg['Phyg'/9623, l='MpServer', x=-404.66, y=80.00, z=707.85], EntityAerbunny['Aerbunny'/9112, l='MpServer', x=-552.83, y=55.98, z=665.43], EntityPhyg['Phyg'/9624, l='MpServer', x=-404.00, y=80.00, z=709.75], EntityPhyg['Phyg'/9625, l='MpServer', x=-405.80, y=80.00, z=705.64], EntityMoa['Moa'/9626, l='MpServer', x=-406.23, y=80.00, z=699.83], EntityPhyg['Phyg'/9642, l='MpServer', x=-437.50, y=61.00, z=726.50], EntityPhyg['Phyg'/9643, l='MpServer', x=-437.50, y=61.00, z=726.50], EntityPhyg['Phyg'/9644, l='MpServer', x=-436.50, y=62.00, z=725.50], EntityPhyg['Phyg'/9645, l='MpServer', x=-435.50, y=61.00, z=725.50], EntityPhyg['Phyg'/7669, l='MpServer', x=-559.51, y=36.00, z=606.36]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:401)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 166125880 bytes (158 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.38 Powered by Forge 13.20.0.2263 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2263.jar) 
	UCHIJAAAA	forge{13.20.0.2263} [Minecraft Forge] (forge-1.11.2-13.20.0.2263.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJAAAA	movillages{1.5.3} [Mo' Villages] ([1.11]MoVillages-1.5.3.jar) 
	UCHIJAAAA	aether_legacy{v1.4} [Aether Legacy] (aether_legacy-1.11.2-1.4.jar) 
	UCHIJAAAA	betterbedrockgen{6.0.1} [BetterBedrockGen] (BBG-1.11.2.jar) 
	UCHIJAAAA	mujmajnkraftsbettersurvival{1.2.1} [Better Survival] (BetterSurvival-1.2.1.jar) 
	UCHIJAAAA	examplemod{1.0} [examplemod] (Death-Bags-Mod-1.11.2.jar) 
	UCHIJAAAA	dbag{1.11.2-3.0} [Death Bags] (Death-Bags-Mod-1.11.2.jar) 
	UCHIJAAAA	environmentalcreepers{1.1.3} [Environmental Creepers] (EnvironmentalCreepers-1.11.2-1.1.3.jar) 
	UCHIJAAAA	lucky{7.4.0} [Lucky Block] (LuckyBlock_1-11_v7-4-0.zip) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics'
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2263
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4358, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Celeron(R) CPU N2830 @ 2.16GHz


![image](https://user-images.githubusercontent.com/29665878/27503888-c10b6514-5846-11e7-9ae8-800dbcdb67ca.png)
Here is a screenshot of the dissapearing hud glitch.

![image](https://user-images.githubusercontent.com/29665878/27503728-b5b77c22-5844-11e7-8340-a0942a95380d.png)
 Here is the photo of the gamecrash message (the "veiw crash report" button doesn't work)

**Comment by KingPhygieBoo** [comment]
For the "Dissapearing HUD glitch", did you try pressing F1?

**Comment by skadooshbag** [comment]
@KingPhygieBoo  forgot that was a thing. thanks. works like a charm.


also, as a general note, I have since recieve the "sheepuf puff thir wool to float" protip, indiciating that the foating sheep thig was not in fact a bug.

**Comment by skadooshbag** [comment]
@KingPhygieBoo 

whoops, forgot that was a thing.

well whatdoyaknow, thanks man.

**Comment by KingPhygieBoo** [comment]
Yup, that's why they are called "Shee_puff_" ;)

**Comment by KingPhygieBoo** [comment]
All of these issues appear to have been fixed, closing the issue.
