### ISSUE TITLE
Everytime I look at a skyroot log, WailaHarvestability crashes and reloads after 30 seconds or so.

### ISSUE THREAD

**Issue by JonathanTheInsane** [Modding-Legacy/Aether-Legacy#155]
WailaHarvestability shows <ERROR> in Waila for 30 seconds and then reloads and works again. Lol.

`[22:47:20] [Client thread/WARN] [Waila]: Catched unhandled exception : [class squeek.wailaharvestability.WailaHandler] java.lang.NullPointerException`

**Comment by Lachney** [comment]
Tested with:

* Aether Legacy 1.4.1 for 1.10.2
* Aether Legacy 1.0.1 for 1.11.2
* WailaHarvestability-mc1.11-1.1.10.jar
* WailaHarvestability-mc1.10.2-1.1.10.jar
* Waila-1.7.1_1.11.2.jar 
* Waila-1.7.0-B3_1.9.4.jar

I cannot reproduce the crash with these versions. Try updating Waila and WailaHarvestability and maybe it won't happen anymore?
