### ISSUE TITLE
Skyroot leaves show missing texture in Waila

### ISSUE THREAD

**Issue by JonathanTheInsane** [Modding-Legacy/Aether-Legacy#156]
The title says it all. C++ is better.

**Comment by Lachney** [comment]
I've tested this in:
* Aether Legacy 1.4.1 for 1.10.2
* Aether Legacy 1.0.1 for 1.11.2

Issue is only occuring in 1.10.2.

**Comment by brodycas3** [comment]
Make sure to also check in wawla

**Comment by 115kino** [comment]
Fixed in latest versions of Aether Legacy. If the issue happens again please make a new issue.
