### ISSUE TITLE
There was music for the Sun Spirit fight that was unused, and could be added.

### ISSUE THREAD

**Issue by KingPhygieBoo** [Modding-Legacy/Aether-Legacy#157]

**Comment by jorgeiscool2** [comment]
Legacy doesn't contain music for boss fights. There was unused music but that's the closest we have to boss music. You should know this :^)

**Comment by KingPhygieBoo** [comment]
I was told it was there, but it looped wrong. But yeah I should know.

**Comment by KingPhygieBoo** [comment]
Yeah, I looked in Aether 1.7.3b, and I found fireboss.ogg
