### ISSUE TITLE
Moa egg rate

### ISSUE THREAD

**Issue by brodycas3** [Modding-Legacy/Aether-Legacy#16]
Please nerf the moa egg drop rate, This is insane.

http://i.imgur.com/8byVoFT.png

**Comment by SansIsTyping** [comment]
Agreed, although isn't this something you should ask in the Discord?

**Comment by brodycas3** [comment]
........

**Comment by 115kino** [comment]
Egg drop rates shall be nerfed

**Comment by 115kino** [comment]
Moa egg rates have increased however i'll need player input to ensure it is fine. (feel free to message me if it needs more tweaking)
