### ISSUE TITLE
[1.11.2] Portal Frame only works when facing East/West

### ISSUE THREAD

**Issue by MokahTGS** [Modding-Legacy/Aether-Legacy#162]
The portal frame refuses to ignite with a bucket of water when oriented north and south.  It works fine if oriented East/West.  Pretty weird.

**Comment by KingPhygieBoo** [comment]
Which version of Minecraft is this on?

**Comment by MokahTGS** [comment]
It was in the title but 1. 11. 2

**Comment by KingPhygieBoo** [comment]
Oh sorry I'm blind haha, I'll test it right away

**Comment by KingPhygieBoo** [comment]
Seems to work fine for me either way.
![2017-07-21_12 27 50](https://user-images.githubusercontent.com/17862210/28475064-802723d2-6e10-11e7-9713-65efc5637e66.png)

**Comment by MokahTGS** [comment]
no idea but I had to go into creative to get the gate to work.  The water would pour in, the portal would flash for a moment and then it would fail and water would go everywhere.

**Comment by KingPhygieBoo** [comment]
Oh, let me check in survival

**Comment by KingPhygieBoo** [comment]
Nope. Seems to be working.

**Comment by jredfox** [comment]
Works as well as in the offhand are you in 1.11.2? Works for 1.10.2

**Comment by KingPhygieBoo** [comment]
1.10.2 should work as well.

**Comment by jredfox** [comment]
It works in newest try updating
