### ISSUE TITLE
Sun Spirit repeats certain lines

### ISSUE THREAD

**Issue by KingPhygieBoo** [Modding-Legacy/Aether-Legacy#163]
Repeating messages:
"Perhaps you are ignorant. Do you wish to know who I am?"
"Do you wish to challenge the might of the sun? You are mad."
"Do not further insult me or you will feel my wrath."
"This is your final warning. Leave now or prepare to burn."

**Comment by catbryce** [comment]
the line about (the sun never setting as long as i am alive) should be removed because its no longer true

**Comment by 115kino** [comment]
Can no longer reproduce this issue in the latest hotfix. If this issue does occur in he new release feel free to open a new issue.
