### ISSUE TITLE
PLS i realy realy realy .... want it for 1.7.10 !

### ISSUE THREAD

**Issue by thejujuofficiel** [Modding-Legacy/Aether-Legacy#164]
Pls can someone make aether 1 for 1.7.10 i fucking realy want it cause he was FUCKING better and i want to open a server with that mod ! I hope someone can do it ! U ARE MY HERO !

**Comment by KingPhygieBoo** [comment]
A port to 1.7.10 is not planned, however if the fan demands are high it will be considered!
