### ISSUE TITLE
Zephers just randomly despawn

### ISSUE THREAD

**Issue by brodycas3** [Modding-Legacy/Aether-Legacy#17]
Even when attacking them

**Comment by 115kino** [comment]
Can you describe or take a picture of how and when they despawn? (ex. in blocks, stuck on blocks, colliding entities, etc...)

**Comment by brodycas3** [comment]
They just despawn when in the air. They don't get stuck or anything that would cause them to despawn.

**Comment by 115kino** [comment]
How far away where you from them?

**Comment by brodycas3** [comment]
A minimum of 8 blocks.

**Comment by brodycas3** [comment]
Look at the left one. http://i.imgur.com/yZ5paen.gifv
Also, they shoot their balls above our heads and the balls also randomly despawn

**Comment by brodycas3** [comment]
That one is far away but they even despawn right in front of you.

**Comment by 115kino** [comment]
They have a special condition where they will despawn to ensure your world doesn't get overrun by Zephyr's and Aerwhale's.
