### ISSUE TITLE
Default Aether Dimension With Default Config Conflicts with Aether II

### ISSUE THREAD

**Issue by jredfox** [Modding-Legacy/Aether-Legacy#175]
The default dimension id aether one: 4, dungeon dimension aether ii dungeon: 4

  this.aetherDimID = getInt(this.DIMENSIONS, "Aether Dimension ID", 3);
  this.sliderLabyrinthDimID = getInt(this.DIMENSIONS, "Slider's Labyrinth Dimension ID", 4);

Also the aether ii seems to have no dimension config since I just looked at the actual file

**Comment by KingPhygieBoo** [comment]
You can change this in the config.

**Comment by jredfox** [comment]
No it's a bug if the default is configed to specifically conflict with the aether ii as if your not suppose to use it

**Comment by jredfox** [comment]
This is not invalid

**Comment by KingPhygieBoo** [comment]
Aether II compatibility is not going to be added, you can easily change it in the configs, that's why it is there.

**Comment by jredfox** [comment]
It's specifaclly meant to be non conflicted by default since it's not conflicting with the moolands which is dimension id default of 5 so I would assume it's not suppose to conflict by default to the aether ii. 

It's literally one line of code
dimension id = config.get(param,param,defaultvalue).getInt(defaultvalue)

**Comment by jredfox** [comment]
So when the coder changes the default value from 4 to 6 all issues would be solved

**Comment by KingPhygieBoo** [comment]
Moolands is not meant to conflict with Aether Legacy, since they are both Modding Legacy mods. Aether II is completely seprate.

**Comment by KingPhygieBoo** [comment]
As I said, it would mess up everyone's worlds, and will not be added, just change it in the config like I said.

**Comment by jredfox** [comment]
No it's not. Literally just all they have to do is change one number for compatibility for their mods team. It's the same aether team deving legacy so it shouldn't conflict with any of their mods 

talk to kino don't make assumptions

**Comment by jredfox** [comment]
Yes you can config it but, most people would assume they don't have to since it's made by the same team.

**Comment by KingPhygieBoo** [comment]
Modding Legacy develops Aether Legacy, Gilded Games develops Aether II.

**Comment by jredfox** [comment]
Kino was appart of gilded games for years I spoke to oscar

**Comment by KingPhygieBoo** [comment]
He is no longer part of Gilded Games, can you please stop arguing with me?
