### ISSUE TITLE
Boats on quicksoil gain infinite velocity/speed

### ISSUE THREAD

**Issue by susieqt** [Modding-Legacy/Aether-Legacy#176]
Found this while transporting villagers on the official server (since apparently feeding villagers doesn't work on here (side note: might have someone look into that too)
when riding a boat (with a villager in it, but i dont think that would affect it) across a quicksoil road, the boat accelerates super fast and never slows down, just gaining speed forever, and if you turn even the slightest bit it results in you spinning uncontrollably forever (since boats appear to be completely unable to slow down at all on quicksoil)
this doesn't seem to have the same effect on minecarts, while you can use quicksoil to avoid needing powered rails, they don't gain infinite speed and spiral out of control

**Comment by 115kino** [comment]
Currently the speed of quicksoil is due to its slipperiness which minecraft handles by itself meaning I can lower the slipperiness but that doesn't mean it will fix the problem.

**Comment by KingPhygieBoo** [comment]
A similar effect happens on Ice/Packed Ice with vanilla, so I don't believe this is Aether's fault
