### ISSUE TITLE
Moa's do not have as much health as they did in the original.

### ISSUE THREAD

**Issue by catbryce** [Modding-Legacy/Aether-Legacy#178]
a diamond sword 3.5 hearts per hit 3.5 times 6 = 21 this is enough to kill moas so there exact health is below that if we round it to 3 times 6 we get 18 this is not enough to kill a moa so there exact health is 20 full hearts or 40 half hearts i tested in aether 1.2.5 to get a more precise measurement

**Comment by catbryce** [comment]
i don't know what 6 hits with a diamond swords translates to in health but moas where definitely tougher in aether 1 unless diamond swords where weaker in1.2.5

**Comment by catbryce** [comment]
also moas with saddles did not run around or wander

**Comment by KingPhygieBoo** [comment]
That's what the Nature staff is for.

**Comment by catbryce** [comment]
you mean they can be told to stay or follow or wander

**Comment by KingPhygieBoo** [comment]
Yes.

**Comment by KingPhygieBoo** [comment]
They can't be told to follow, that was never a thing.

**Comment by catbryce** [comment]
did not Know that thank you

**Comment by catbryce** [comment]
riding them is better than following

**Comment by catbryce** [comment]
this has been up for a long time dose that mean its being added

**Comment by KingPhygieBoo** [comment]
It just means Kino hasn't gotten to it yet.

**Comment by catbryce** [comment]
i want to apologize for making such a big deal about the notch hammers

**Comment by catbryce** [comment]
can i help fix this and other issues

**Comment by KingPhygieBoo** [comment]
Going to test Aether I to check if this is true, and then I will fix it

**Comment by catbryce** [comment]
thank you how much health did they have in the original
