### ISSUE TITLE
Aether Portals not letting entitys through, like Vanilla.

### ISSUE THREAD

**Issue by catbryce** [Modding-Legacy/Aether-Legacy#179]
mounts that your riding should come with you when you fall out of the aether or go thru the aether portals.

**Comment by catbryce** [comment]
i know that moas bunnys and other mounts did go down to earth when you where riding them in aether 1 none of the portals let anything but humans thru in 1.2.5 but now that vanilla portals do let all the other mobs in and out it makes sense that the aether portal should to

**Comment by catbryce** [comment]
im new to reporting issues i hope im not being annoying

**Comment by 115kino** [comment]
Entities will not be allowed to teleport to the Aether on their own. Only mounts and passengers will teleport to the aether with you.
