### ISSUE TITLE
Lag spikes in Singleplayer

### ISSUE THREAD

**Issue by LuciferCZ** [Modding-Legacy/Aether-Legacy#18]
Local singleplayer servers get a lot of lag after a while of playing, this affects gameplay.
However this does not happen on multiplayer servers for some reason.

**Comment by 115kino** [comment]
Can you please describe when these lag spikes happen and how frequently these occur?

**Comment by LuciferCZ** [comment]
Basically, the mod is unplayable in Singleplayer for me lagspikes occur in about 10 seconds into singleplayer. I'm most certain that it is not my computer cause all other mods work fine.

**Comment by TheCorruption** [comment]
Try adding more RAM.

**Comment by DanielN10** [comment]
I can confirm this. As soon as I added this mod, the lab is unbearable.

**Comment by 115kino** [comment]
I'm looking into fixing performance issues for the upcoming release.

**Comment by 115kino** [comment]
LuciferCZ and DanielN10 there are more improvements to v1.4, if the lag is still unbearable please feel free to create a new issue. (The lag could also be a result of not being able to run Minecraft well but I can't say for sure)
