### ISSUE TITLE
notch hammer should not have a cooldown in 1.8 or below leave cooldowns in 1.9 and up where they belong

### ISSUE THREAD

**Issue by catbryce** [Modding-Legacy/Aether-Legacy#181]

**Comment by 115kino** [comment]
Explain?

**Comment by catbryce** [comment]
havent seen 1.7 or 1.8 so i dont know if its in there just think cooldowns dont make any sense in 1.8 or 1.7

**Comment by 115kino** [comment]
The Hammer of Notch will always have an ability cooldown no matter what version it is in

**Comment by catbryce** [comment]
ok your right i tryed the hammer in creative and its way to easy to annihilate everything
