### ISSUE TITLE
Certain Silver dungeons are impossible.

### ISSUE THREAD

**Issue by HeroErik312** [Modding-Legacy/Aether-Legacy#187]
[1.11.2] Silver Dungeons are usually not made able beacouse walls blocks the way

**Comment by catbryce** [comment]
you mean raid able as in you cant get in

**Comment by Lachney** [comment]
@HeroErik312 Are all the silver dungeons you encounter generating this way or some?

**Comment by KingPhygieBoo** [comment]
This is a rare bug.

**Comment by SolidSyndrome** [comment]
i just started playing and i had 4 silver dungeons all spawn within about 16 chunks of each-other and all of them were not completable without breaking down at least two walls in creative to progress. i could also break those blocks with yellow squares on them when they were on the floor for some reason...

**Comment by 115kino** [comment]
Has been fixed. There will always be an entrance to any silver dungeons you find.
