### ISSUE TITLE
[1.11.2] The Cristmas tree never spawns in the aether

### ISSUE THREAD

**Issue by HeroErik312** [Modding-Legacy/Aether-Legacy#188]

**Comment by Lachney** [comment]
This is actually an option you have to manually enable in your Aether Legacy.cfg

Look in your minecraft installation and navigate to the following folder
config/aether/Aether Legacy.cfg

The option you want to edit is

```
"aether world generation" {
    B:"Christmas Content"=false
}
```

**Comment by HeroErik312** [comment]
thanks i dont knowed about that

**Comment by Lachney** [comment]
Welcome! If you have any other issues feel free to submit more issues to our issue tracker.
You should also check out this neat little thing here. @HeroErik312 
https://waffle.io/Modding-Legacy/Aether-Legacy
