### ISSUE TITLE
beds should ether explode or let you sleep in the aether currently they don't do anything

### ISSUE THREAD

**Issue by catbryce** [Modding-Legacy/Aether-Legacy#189]

**Comment by 115kino** [comment]
They are intentionally made to do nothing as to prevent players from blowing up their hard work. Beds shall stay doing nothing.

**Comment by catbryce** [comment]
so you cant sleep aether ether

**Comment by KingPhygieBoo** [comment]
You can't respawn in the Aether, there would be no point.

**Comment by catbryce** [comment]
just to make it day

**Comment by KingPhygieBoo** [comment]
You would have to modify the bed somehow.

**Comment by catbryce** [comment]
also why wood you put a bed in your aether house if it dose nothing or explodes

**Comment by KingPhygieBoo** [comment]
For decoration if anything. Kino has already said he's keeping it the same.

**Comment by catbryce** [comment]
ok i will let it go

**Comment by catbryce** [comment]
can they have a message saying  you may not sleep in the aether
