### ISSUE TITLE
Double drops

### ISSUE THREAD

**Issue by LuciferCZ** [Modding-Legacy/Aether-Legacy#19]
Axes double drop logs and so does pickaxes on holystone.

**Comment by LuciferCZ** [comment]
Couldn't replicate what happend with the axes although the pickaxe was able to be replicated.
https://gyazo.com/b85568c60885a9f83c0877c96deb67e2

Also i noticed Skyroot pickaxes are much more faster than Zanite and Holystone pickaxes.

**Comment by LuciferCZ** [comment]
Works with all skyroot tools.

**Comment by 115kino** [comment]
Skyroot tools have a special double drop ability.

Zanite tools slowly get better the more worn out it is. (Eventually being faster than diamond tools)
