### ISSUE TITLE
Can't dismount Aether mobs that are mounting something else.

### ISSUE THREAD

**Issue by catbryce** [Modding-Legacy/Aether-Legacy#190]
if your on a moa that is in a boat you can`t get of not sure if other mounts have this problem

**Comment by KingPhygieBoo** [comment]
I believe this is a problem with Vanilla too, if you get a Horse or Saddled Pig into a Minecart/Boat.

**Comment by catbryce** [comment]
i wood not know much about it i am only playing aether 1.10 for testing until aether 1.7.10 comes out

**Comment by 115kino** [comment]
There is a temporary fix for this in the latest release of Aether Legacy. A solution will be worked on for future releases.
