### ISSUE TITLE
Dungeon chests do not work properly if you open them for the first time

### ISSUE THREAD

**Issue by ItzDennisz** [Modding-Legacy/Aether-Legacy#192]
Dungeon chests have to be closed and then reopened in order for them to not glitch out completely.

**Comment by KingPhygieBoo** [comment]
I can't seem to reproduce this. @ItzDennisz could you be a bit more specific on "Glitch out completley"?

**Comment by ItzDennisz** [comment]
When you beat a boss and use the key to open the treasure chest, the inventory will glitch out.
Items dissapearing and reappearing in other slots

**Comment by KingPhygieBoo** [comment]
I actually managed to find this by accident, changing to Confirmed.

**Comment by 115kino** [comment]
Dungeon chests reworked. If the problem occurs feel free to make a new issue regarding it.
