### ISSUE TITLE
The accessory button is not removed when switching tabs in creative mode.

### ISSUE THREAD

**Issue by ItzDennisz** [Modding-Legacy/Aether-Legacy#194]
When opening your creative inventory (And if the selected tab is Survival Inventory when you open it), switching to other creative tabs will not get rid of the cloud button.

If you open the creative inventory and the selected tab is NOT Survival Inventory, switching to Survival Inventory will not show the cloud button.

![image](https://user-images.githubusercontent.com/13542400/29941574-4e693c38-8e93-11e7-994c-426fb513c307.png)

**Comment by Lachney** [comment]
A rendering issue, confirmed!

**Comment by KingPhygieBoo** [comment]
If you aren't in the "Survival Inventory" tab, and you switch to it, the button isn't there until you reopen your inventory.

**Comment by ItzDennisz** [comment]
thats what i said.

**Comment by KingPhygieBoo** [comment]
No you said the opposite, either way it's still a bug.

**Comment by ItzDennisz** [comment]
''If you open the creative inventory and the selected tab is NOT Survival Inventory, switching to Survival Inventory will not show the cloud button.''
...

**Comment by KingPhygieBoo** [comment]
Oh woops, sorry

**Comment by 115kino** [comment]
Fixed in the latest versions of Aether Legacy
