### ISSUE TITLE
Serverside lag causes you to be sent to the top of the Aether when falling out.

### ISSUE THREAD

**Issue by catbryce** [Modding-Legacy/Aether-Legacy#195]

**Comment by Lachney** [comment]
@catbryce What version on Minecraft?

**Comment by catbryce** [comment]
1.10.2 it dosint hapen every time

**Comment by Lachney** [comment]
All right thank you. I will try and reproduce the issue on 1.10.2 then try to reproduce on 1.11.2

**Comment by KingPhygieBoo** [comment]
This used to happen. This only happens when the game is lagging serverside.

**Comment by 115kino** [comment]
Fixed in the latest versions of Aether Legacy
