### ISSUE TITLE
can the old zepyer be added and share the sky with the current one as a variant

### ISSUE THREAD

**Issue by catbryce** [Modding-Legacy/Aether-Legacy#198]
![29995886-412d756a-8fb1-11e7-8abe-89f54d9bfd2d](https://user-images.githubusercontent.com/31258485/29996002-9b48ea28-8fb3-11e7-9a09-1c38d9961d09.png)

**Comment by KingPhygieBoo** [comment]
I think we're just sticking to the current one, as it would probably be confusing.
