### ISSUE TITLE
i found crystal tree saplings in the texturs of aether 1

### ISSUE THREAD

**Issue by catbryce** [Modding-Legacy/Aether-Legacy#199]
it makes no sense for any of the trees to not have saplings
![aetherblocks](https://user-images.githubusercontent.com/31258485/29998614-eecac782-8fec-11e7-984c-fe92d1f9ca1d.png)

**Comment by KingPhygieBoo** [comment]
The unused textures were already discussed early in Aether Legacy's development, there will be no more content additions to 1.10+. This is planned for the official Aether Legacy addon we are going to develop eventually, as well as the 1.7.10 version.

**Comment by catbryce** [comment]
sorry did not know

**Comment by catbryce** [comment]
when will 1.7.10 aether be released i really dont care about anything above that
