### ISSUE TITLE
Blueberry bushes makes you fall in a continuous loop

### ISSUE THREAD

**Issue by LuciferCZ** [Modding-Legacy/Aether-Legacy#20]
Blueberry bushes makes you fall in a continuous loop when standing ontop of them whilst harvesting.

https://gyazo.com/064ec2cbe8641fa54ebf1bc8a80a2bd6

**Comment by 115kino** [comment]
The only way to fix such a problem is to remove the hitbox for berry bushes. (Removed in v1.3)
