### ISSUE TITLE
unused textures please use them

### ISSUE THREAD

**Issue by catbryce** [Modding-Legacy/Aether-Legacy#200]
moa armor 

![mos](https://user-images.githubusercontent.com/31258485/29998675-9c1b8c2c-8fee-11e7-87e8-ebb0317e439d.png)

![moa](https://user-images.githubusercontent.com/31258485/29998688-d21fb474-8fee-11e7-93ad-f762561b4c52.png) orange moa already added
![aetheritems](https://user-images.githubusercontent.com/31258485/29998722-92bf1e5e-8fef-11e7-895a-ce9beea39355.png)

**Comment by KingPhygieBoo** [comment]
As I said, there will be no new content additions, these will be in 1.7.10 Aether Legacy and under, as well as the Official Aether Legacy addon.

**Comment by KingPhygieBoo** [comment]
This includes the Shields, Phoenix Tools, Pink Aercloud, Hammer of Jeb, Platinum Key, Aerwhale Egg, Swetty Ball, Crystal Saplings, and Holiday Saplings

**Comment by catbryce** [comment]
sorry when will 1.7.10 aether be released i really dont care about anything above that

**Comment by catbryce** [comment]
sorry when will 1.7.10 aether be released i really don't care about anything above that
