### ISSUE TITLE
 i want to help bug fix aether 1.7.10

### ISSUE THREAD

**Issue by catbryce** [Modding-Legacy/Aether-Legacy#201]
when will 1.7.10 aether be released i really dont care about anything above that i have put up with 1.10 and 1.11 only to help this project

**Comment by KingPhygieBoo** [comment]
1.7.10 isn't priority at the moment, I don't know how far @115kino has gotten with it, I know there's other versions being worked on at the moment.

**Comment by catbryce** [comment]
ok when it comes out i will try it and report every bug i find.
