### ISSUE TITLE
notch hammer is under powered please hear me out

### ISSUE THREAD

**Issue by catbryce** [Modding-Legacy/Aether-Legacy#203]
shorter cooldown please for the effort that you go thru to get the notch hammer its just not worth it. i was going to let it go but i tested it and a fully drawn bow dose more damage and is about 7 times faster and dart shooters are like machine guns

**Comment by catbryce** [comment]
i really don't what cooldown what line of code is it i will remove it my self for my own use

**Comment by ItzDennisz** [comment]
You should really stop creating issues for reasons like this one.
Issues are meant for bugs or similair problems.

**Comment by catbryce** [comment]
don't deviations form the original aether count it should be in exact recreation

**Comment by catbryce** [comment]
if accuracy is not the goal of this protect then i will just stop

**Comment by catbryce** [comment]
i will admit that many of the issues that i have opened where things that where already fixed or invalid for that i apologize.

**Comment by KingPhygieBoo** [comment]
This isn't really a bug, more of a personal thing. It's supposed to be long and will not be changed

**Comment by catbryce** [comment]
ok i wont bring it up again
