### ISSUE TITLE
The time command doesn't support the longer days.

### ISSUE THREAD

**Issue by catbryce** [Modding-Legacy/Aether-Legacy#205]

**Comment by catbryce** [comment]
probably has something to do with the longer days

**Comment by catbryce** [comment]
is it only the day that is longer or are day and night equally long

**Comment by KingPhygieBoo** [comment]
Just longer days, not nights.

**Comment by 115kino** [comment]
Longer days have been removed. They will be added at a later update.

**Comment by catbryce** [comment]
so long days will be added back when you figure out how to make them work with the time comand

**Comment by KingPhygieBoo** [comment]
They just broke everything, not just the time command.
