### ISSUE TITLE
Spawn rates are quite obnoxious

### ISSUE THREAD

**Issue by catbryce** [Modding-Legacy/Aether-Legacy#206]
not sure if they show up at night ether

**Comment by KingPhygieBoo** [comment]
Can you describe this better? Do you mean not rendering or spawning?

**Comment by KingPhygieBoo** [comment]
They only spawn at night, if it's raining in the Aether that is another bug on it's own

**Comment by catbryce** [comment]
they are out but they are few and far between

**Comment by KingPhygieBoo** [comment]
Okay. They aren't supposed to spawn in masses so that's perfectly normal.

**Comment by catbryce** [comment]
they seem to rare i have looked all over and only seen two

**Comment by 115kino** [comment]
This shouldn't be the case with the longer days being removed (longer days caused issues with spawning). If the issue does occur in the recent versions of Aether Legacy please feel free to make a new issue.
