### ISSUE TITLE
Valkyrie Lances can't be repaired the same way other valkyrie tools can

### ISSUE THREAD

**Issue by susieqt** [Modding-Legacy/Aether-Legacy#208]
Every other Valkyrie tool can be repaired on an anvil with diamonds, same with non-Valkyrie dungeon armor (the armor can also be repaired with enchanted gravitite I believe, but the tools can't, that might be a bug?)
the lance, however, can't be repaired the same way, it won't accept either diamonds or gravitite

**Comment by 115kino** [comment]
Fixed in the latest versions of Aether Legacy
