### ISSUE TITLE
bronze dungeons completely buried with no hallways 

### ISSUE THREAD

**Issue by catbryce** [Modding-Legacy/Aether-Legacy#212]
![2017-09-13_12 06 56](https://user-images.githubusercontent.com/31258485/30393173-7af53e1c-987c-11e7-95b5-00fb7541f277.png)
there is no way to get in with out digging and this kind of thing is common

**Comment by JonathanTheInsane** [comment]
Maybe this was normal in the Aether for 1.2.5? I would assume some dungeons would need to be dug through to be given access too.

**Comment by KingPhygieBoo** [comment]
They normally have a big Holystone/Mossy Holystone hallways

**Comment by JonathanTheInsane** [comment]
Indeed, which is what the X-Ray mod is deciding to leave out, since I see *no other holystone* in the pictures.

**Comment by JonathanTheInsane** [comment]
Perhapes the entrance is made out of holystone and mossy holystone in that case?

**Comment by catbryce** [comment]
its spectator mode not a mod if there was a hallway it wood be visible

**Comment by JonathanTheInsane** [comment]
In spectator mode, any forms of stone are removed from the picture. If it is supposed to show hollow areas, it is a bug with Minecraft's spectator mode. Are you able to get screenshots of inside where there are no walls?

**Comment by catbryce** [comment]
i am certain that there are no hallways i checked the outside of the island and you cant tell that any dungeons are there. also the air in the hall is what wood show not the stone

**Comment by JonathanTheInsane** [comment]
I'll leave this one to Bailey and Kino to check out then.
