### ISSUE TITLE
gravitite seems to generate higher than normal?

### ISSUE THREAD

**Issue by susieqt** [Modding-Legacy/Aether-Legacy#213]
i just found some gravitite at y=40, and I've found it as high as y=50 before (but previously I had assumed it had just floated up there from somewhere, this is the first time I've seen it this high where it couldn't have floated up) when normally I'm pretty sure its supposed to just generate near the bottom of islands (like diamond)
here's a screenshot since this would be pretty difficult to reproduce given how ore generation works http://puu.sh/xyVjb/5be79968fa.png
as I was about to post this I found some more like this http://puu.sh/xyVzC/49442ac4d4.jpg

**Comment by 115kino** [comment]
Fixed in the latest versions of Aether Legacy
