### ISSUE TITLE
Gravitite Chestplates are misspelled 

### ISSUE THREAD

**Issue by aberg12** [Modding-Legacy/Aether-Legacy#214]
Hello all,

I noticed while playing that Gravitite chestplates are misspelled. See attached screenshot.

Happy Mining,
aberg12
![screenshot 597](https://user-images.githubusercontent.com/31937487/30398709-5c353874-989f-11e7-84e5-8bedfbae42eb.png)

**Comment by JonathanTheInsane** [comment]
I love it. Maybe the entire en_US.lang and relative files can use some revising?

**Comment by KingPhygieBoo** [comment]
That's the only typo that's been seen

**Comment by JonathanTheInsane** [comment]
Well then that should be easy to fix

**Comment by aberg12** [comment]
Yeah I hope that helps you guys out. Also I've always loved the aether 1. I
was really happy to find this mod. Aether 2 just isn't the same.

**Comment by JonathanTheInsane** [comment]
Aether 2 will never be the same. All hail the 1.7.3beta version.

**Comment by aberg12** [comment]
True,
That update looks pretty cool. I still appreciate the work you guys did to
update aether 1. Do you know of any dedicated servers that I could play on
with this mod?

**Comment by JonathanTheInsane** [comment]
This might be the last post I send before Bailey locks the conversation, but here is the IP to the Official Aether Legacy server: moddinglegacy.com

Cheers!

**Comment by 115kino** [comment]
Fixed. Sadly this was an actual issue...
