### ISSUE TITLE
any thing you ride down from the aether disappears 

### ISSUE THREAD

**Issue by catbryce** [Modding-Legacy/Aether-Legacy#215]
moas, bunnys, flying cows, flying pigs, and if you open a paracute in the aether it gose away when you re enter the overworld and you have to reopen it in Aether 1 all of them wood stay with you if you fell

**Comment by KingPhygieBoo** [comment]
Related to #179

**Comment by catbryce** [comment]
i felt this needed its own issue

**Comment by KingPhygieBoo** [comment]
I just put that there anyway

**Comment by 115kino** [comment]
Fixed in the latest versions of Aether Legacy
