### ISSUE TITLE
mobs move as fast on bottom holystone brick slabs as they do on quicksoil

### ISSUE THREAD

**Issue by susieqt** [Modding-Legacy/Aether-Legacy#216]
I haven't tried it with aether mobs yet, but skeletons and zombies at least will run extremely fast when on a platform of bottom holystone slabs, idk if the block underneath the slab affects it any, but I know it happens with air and water underneath them at least

**Comment by susieqt** [comment]
actually upon further testing it seems like its only skeletons and MAYBE spiders that do it? (I cant tell if spiders are moving faster because they move so quickly already), the skeletons definitely are running at super high speeds though

**Comment by KingPhygieBoo** [comment]
I believe this happens with all slabs, on any slippery block. Going to test this now.

**Comment by KingPhygieBoo** [comment]
Yes, this is an issue with Vanilla, and is not Aether related.
