### ISSUE TITLE
Server is skipping ticks and timeout players' connection when checking for donator

### ISSUE THREAD

**Issue by Nitix** [Modding-Legacy/Aether-Legacy#217]
When a player is connecting to server, the server will skip a lot of ticks and players' connection will timeout.
This issue happen when the site : http://www.gilded-games.com is down. The server waits for the connection that will timeout, the server will also do nothing else while waiting.

The issue is located at : https://github.com/Modding-Legacy/Aether-Legacy/blob/59ed80de1ba57855c4c3804e6882cdb7742d3768/src/main/java/com/legacy/aether/common/player/perks/AetherPerks.java#L73

**Comment by ItzDennisz** [comment]
Should do this asynchronously or set a max amounts of ticks.

**Comment by Nitix** [comment]
Asynchronously but not with the minecraft engine, it's currently running asynchronously, but synchronously with the game loop.

**Comment by MineProjectZ** [comment]
i have the same error. Please fix it.

**Comment by Nitix** [comment]
To add more info: 
https://github.com/Modding-Legacy/Aether-Legacy/blob/59ed80de1ba57855c4c3804e6882cdb7742d3768/src/main/java/com/legacy/aether/common/player/PlayerAetherEvents.java#L164

Is using internal game engine that will make running the thread in sync with the game loop.

**Comment by 115kino** [comment]
Donator perks will be available to everyone as of now. I will be removing every check for donator status.
