### ISSUE TITLE
Please add this zh_CN.lang

### ISSUE THREAD

**Issue by jiastku98** [Modding-Legacy/Aether-Legacy#219]
I translate this mod into Chinese.
Please add this lang!
Thank U!
I think 99% are right!

Google Drive：
https://drive.google.com/open?id=0B2hZh6VqmnKHWTlkc1dqZnZldFk

`

# Haku98翻译
# Email:jiastku98@outlook.com
# Item Names
item.lore_book.name=知识之书
item.MoaEgg.name=恐鸟蛋
item.leather_gloves.name=皮革手套
item.chain_gloves.name=链手套
item.golden_gloves.name=金手套
item.iron_gloves.name=铁手套
item.diamond_gloves.name=钻石手套
item.zanite_gloves.name=紫玉手套
item.gravitite_gloves.name=重力手套
item.neptune_gloves.name=海王星手套
item.phoenix_gloves.name=凤凰手套
item.obsidian_gloves.name=黑曜石手套
item.valkyrie_gloves.name=女武神手套
item.skyroot_pickaxe.name=天根树镐
item.skyroot_axe.name=天根树斧
item.skyroot_shovel.name=天根树铲
item.holystone_pickaxe.name=圣石镐
item.holystone_axe.name=圣石斧
item.holystone_shovel.name=圣石铲
item.zanite_pickaxe.name=紫玉镐
item.zanite_axe.name=紫玉斧
item.zanite_shovel.name=紫玉铲
item.gravitite_pickaxe.name=重力镐
item.gravitite_axe.name=重力斧
item.gravitite_shovel.name=重力铲
item.valkyrie_pickaxe.name=女武神镐
item.valkyrie_axe.name=女武神斧
item.valkyrie_shovel.name=女武神铲
item.skyroot_sword.name=天根树剑
item.holystone_sword.name=圣石剑
item.zanite_sword.name=紫玉剑
item.gravitite_sword.name=重力剑
item.flaming_sword.name=燃烧的剑
item.lightning_sword.name=闪电剑
item.holy_sword.name=神圣之剑
item.lightning_knife.name=闪电匕首
item.candy_cane_sword.name=拐杖糖剑
item.vampire_blade.name=吸血鬼之剑
item.pig_slayer.name=杀猪刀
item.valkyrie_lance.name=女武神长枪
item.notch_hammer.name=Notch之锤
item.dart_shooter_golden.name=金飞镖枪
item.dart_shooter_poison.name=毒药飞镖枪
item.dart_shooter_enchanted.name=附魔飞镖枪
item.phoenix_bow.name=凤凰弓
item.zanite_helmet.name=紫玉头盔
item.zanite_chestplate.name=紫晶胸甲
item.zanite_leggings.name=紫玉护腿
item.zanite_boots.name=紫玉靴子
item.gravitite_helmet.name=重力头盔
item.gravitite_chestplate.name=重力胸甲
item.gravitite_leggings.name=重力护腿
item.gravitite_boots.name=重力靴子
item.neptune_helmet.name=海王星头盔
item.neptune_chestplate.name=海王星胸甲
item.neptune_leggings.name=海王星护腿
item.neptune_boots.name=海王星靴子
item.phoenix_helmet.name=凤凰头盔
item.phoenix_chestplate.name=凤凰胸甲
item.phoenix_leggings.name=凤凰护腿
item.phoenix_boots.name=凤凰靴子
item.obsidian_helmet.name=黑曜石头盔
item.obsidian_chestplate.name=黑曜石胸甲
item.obsidian_leggings.name=黑曜石护腿
item.obsidian_boots.name=黑曜石靴子
item.valkyrie_helmet.name=女武神头盔
item.valkyrie_chestplate.name=女武神胸甲
item.valkyrie_leggings.name=女武神护腿
item.valkyrie_boots.name=女武神靴子
item.sentry_boots.name=哨兵靴子
item.blue_berry.name=蓝色的浆果
item.gummy_swet_blue.name=蓝色黏性史维特
item.gummy_swet_golden.name=金色黏性史维特
item.white_apple.name=白色的苹果
item.candy_cane.name=拐杖糖
item.ginger_bread_man.name=姜饼人
item.healing_stone.name=治疗石头
item.iron_pendant.name=铁吊坠
item.golden_pendant.name=金吊坠
item.zanite_pendant.name=紫玉吊坠
item.ice_pendant.name=冰吊坠
item.iron_ring.name=铁戒指
item.golden_ring.name=金戒指
item.zanite_ring.name=紫玉戒指
item.ice_ring.name=冰戒指
item.white_cape.name=白色披风
item.red_cape.name=红色披风
item.blue_cape.name=蓝色披风
item.yellow_cape.name=黄色披风
item.swet_cape.name=史维特披风
item.valkyrie_cape.name=瓦尔基披风
item.invisibility_cape.name=隐身披风
item.agility_cape.name=敏捷披风
item.repulsion_shield.name=排斥之盾
item.regeneration_stone.name=恢复之石
item.golden_feather.name=金色羽毛
item.iron_bubble.name=铁泡沫
item.aechor_petal.name=毒箭草花瓣
item.ambrosium_shard.name=以太碎片
item.zanite_gemstone.name=紫玉宝石
item.skyroot_stick.name=天根树木棍
item.golden_amber.name=金琥珀
item.aether_spawn_egg.name=生成
item.skyroot_bucket_empty.name=天根树桶
item.skyroot_bucket_water.name=天根树水桶
item.skyroot_bucket_poison.name=天根树毒药桶
item.skyroot_bucket_remedy.name=天根树治疗桶
item.skyroot_bucket_milk.name=天根树牛奶桶
item.aether_tune.name=以太曲调
item.ascending_dawn.name=黎明升起
item.welcoming_skies.name=欢迎天空
item.victory_medal.name=胜利奖牌
item.life_shard.name=生活碎片
item.cloud_staff.name=云权杖
item.nature_staff.name=自然权杖
item.dungeon_key_bronze.name=青铜钥匙
item.dungeon_key_silver.name=银钥匙
item.dungeon_key_golden.name=金钥匙
item.cold_parachute.name=寒冷的降落伞
item.golden_parachute.name=金降落伞
item.dart_golden.name=金飞镖
item.dart_poison.name=毒药飞镖
item.dart_enchanted.name=附魔飞镖
item.enchanted_blueberry.name=附魔浆果

# Block Names
tile.aether_portal.name=以太传送门
tile.aether_grass.name=以太草方块
tile.aether_dirt.name=以太泥土
tile.enchanted_aether_grass.name=蕴魔以太草
tile.cold_aercloud.name=寒冷的以太云
tile.blue_aercloud.name=蓝色的以太云
tile.golden_aercloud.name=金色以太云
tile.berry_bush_stem.name=浆果布什阀杆
tile.berry_bush.name=浆果灌木
tile.purple_flower.name=紫色的花
tile.white_flower.name=白色的花
tile.enchanted_gravitite.name=蕴魔重力矿
tile.holystone.name=圣石
tile.mossy_holystone.name=长满青苔的圣石
tile.carved_stone.name=有雕刻的石头
tile.angelic_stone.name=天使石头
tile.hellfire_stone.name=地狱之火石头
tile.sentry_stone.name=哨兵石头
tile.light_angelic_stone.name=光天使石头
tile.light_hellfire_stone.name=光地狱之火石头
tile.ambrosium_ore.name=以太矿石
tile.zanite_ore.name=紫玉矿石
tile.gravitite_ore.name=重力矿石
tile.zanite_block.name=紫玉块
tile.skyroot_log.name=天根树原木
tile.golden_oak_log.name=金橡木原木
tile.green_leaves.name=天根树叶子
tile.golden_oak_leaves.name=金橡木叶子
tile.crystal_fruit_leaves.name=水晶水果叶子
tile.crystal_leaves.name=水晶叶子
tile.decorated_holiday_leaves.name=装饰假期叶子
tile.holiday_leaves.name=假期叶子
tile.skyroot_sapling.name=天根树树苗
tile.golden_oak_sapling.name=金橡木树苗
tile.ambrosium_torch.name=以太火炬
tile.skyroot_plank.name=天根树板材
tile.present.name=现在
tile.pillar.name=支柱
tile.pillar_top.name=支柱顶端
tile.quicksoil.name=流沙
tile.quicksoil_glass.name=流沙玻璃
tile.aerogel.name=气凝胶
tile.icestone.name=冰石
tile.treasure_chest.name=宝藏箱子
tile.enchanter.name=祭坛
tile.incubator.name=孵化器
tile.chest_mimic.name=箱子怪
tile.freezer.name=冰箱
tile.holystone_brick.name=圣石砖
tile.aether_present.name=礼物
tile.skyroot_fence.name=天根树栅栏
tile.carved_wall.name=有雕刻的墙
tile.angelic_wall.name=天使墙
tile.hellfire_wall.name=地狱之火墙
tile.holystone_wall.name=圣石墙
tile.holystone_brick_wall.name=圣石砖墙
tile.mossy_holystone_wall.name=长满青苔的圣石墙
tile.carved_stairs.name=有雕刻的楼梯
tile.angelic_stairs.name=天使楼梯
tile.hellfire_stairs.name=地狱之火楼梯
tile.skyroot_stairs.name=天根树楼梯
tile.mossy_holystone_stairs.name=长满青苔的圣石楼梯
tile.holystone_stairs.name=圣石楼梯
tile.holystone_brick_stairs.name=圣石砖楼梯
skyroot_slab.name=天根树板
tile.skyroot_double_slab.name=天根树双板
carved_slab.name=有雕刻的台阶
tile.carved_double_slab.name=有雕刻的双板
angelic_slab.name=天使板
tile.angelic_double_slab.name=天使双台阶
hellfire_slab.name=地狱之火台阶
tile.hellfire_double_slab.name=地狱之火双台阶
holystone_slab.name=圣石台阶
tile.holystone_double_slab.name=圣石双台阶
mossy_holystone_slab.name=长满青苔的圣石台阶
tile.mossy_holystone_double_slab.name=长满青苔的圣石双台阶
holystone_brick_slab.name=圣石砖台阶
tile.holystone_brick_double_slab.name=圣石砖双台阶
tile.pink_aercloud.name=粉红色的以太云
tile.skyroot_fence_gate.name=天根树栅栏门

# Entities
entity.aether_legacy.aechor_plant.name=毒箭草
entity.aether_legacy.cockatrice.name=毒蛇
entity.aether_legacy.mimic.name=模仿
entity.aether_legacy.sentry.name=哨兵
entity.aether_legacy.zephyr.name=西风
entity.aether_legacy.aerwhale.name=以太鲸
entity.aether_legacy.aerbunny.name=以太兔
entity.aether_legacy.sheepuff.name=以太羊
entity.aether_legacy.valkyrie.name=女武神
entity.aether_legacy.valkyrie_queen.name=女武神女王
entity.aether_legacy.slider.name=滑行者
entity.aether_legacy.sun_spirit.name=太阳精神
entity.aether_legacy.fire_minion.name=火奴才
entity.aether_legacy.mini_cloud.name=迷你云
entity.aether_legacy.tnt_present.name=三硝基甲苯闪烁
entity.aether_legacy.lightning_knife.name=闪电刀
entity.aether_legacy.thunder_ball.name=雷电球
entity.aether_legacy.zephyr_snowball.name=西风雪球
entity.aether_legacy.floating_block.name=浮动块
entity.aether_legacy.parachute.name=降落伞
entity.aether_legacy.golden_dart.name=金飞镖
entity.aether_legacy.poison_dart.name=毒药飞镖
entity.aether_legacy.enchanted_dart.name=附魔飞镖
entity.aether_legacy.fire_ball.name=火球
entity.aether_legacy.ice_ball.name=冰球
entity.aether_legacy.flying_cow.name=以太牛
entity.aether_legacy.phyg.name=以太猪
entity.aether_legacy.swet.name=史维特
entity.aether_legacy.moa.name=恐鸟
entity.aether_legacy.whirly.name=旋风

# Achievements
achievement.enter_aether=敌对的天堂
achievement.blue_aercloud=飞向宇宙,浩瀚无垠!
achievement.grav_tools=粉色是新的蓝色
achievement.incubator=现在你们是一家人了
achievement.enchanter=你相信魔法吗？
achievement.flying_pig=当以太猪飞的时候
achievement.defeat_bronze=就像BOSS一样!
achievement.defeat_silver=退位
achievement.defeat_gold=不复存在
achievement.loreception=领悟

# Achievement Descriptions
achievement.enter_aether.desc=进入以太
achievement.blue_aercloud.desc=在蓝色的以太云上弹跳
achievement.grav_tools.desc=制作一个重力工具
achievement.incubator.desc=孵化一个恐鸟
achievement.enchanter.desc=制作一个祭坛
achievement.flying_pig.desc=骑着以太猪飞
achievement.defeat_bronze.desc=打败青铜地牢BOSS
achievement.defeat_silver.desc=打败白银地牢BOSS
achievement.defeat_gold.desc=打败黄金地牢BOSS
achievement.loreception.desc=阅读知识之书

# Creative Tabs Names
tab.aether_blocks=以太方块
tab.aether_tools=以太工具
tab.aether_weapons=以太武器
tab.aether_armor=以太护甲
tab.aether_food=以太食物
tab.aether_accessories=以太饰件
tab.aether_material=以太材料
tab.aether_misc=以太杂项

# Tab Names
tab.accessories.name=配件

`

**Comment by ItzDennisz** [comment]
You're probably better off creating a pull request for this.

**Comment by KingPhygieBoo** [comment]
Alright, gonna check this out and add it if it's all functioning.

**Comment by KingPhygieBoo** [comment]
Commited and ready to go!
