### ISSUE TITLE
world don't charge when mod is installed

### ISSUE THREAD

**Issue by ralulol1** [Modding-Legacy/Aether-Legacy#225]
i install it and when i want to play it just don´t charge the world, there is no blocks or comands, this happens in all versions of the mod and all of forge in the 1.10.2 or 1.11 pliss help

**Comment by KingPhygieBoo** [comment]
Did you install forge properly, and do other mods work? Where did you download the mod from as well?

**Comment by ralulol1** [comment]
yes forge is well and I downloaded in curseforge normally  the version 1.4.1
[problem.zip](https://github.com/Modding-Legacy/Aether-Legacy/files/1545392/problem.zip) here some footage of what i am talking about

**Comment by KingPhygieBoo** [comment]
This isn't a problem with the mod, this is a performance issue on your side, I would say wait awhile for it to load if anything.
