### ISSUE TITLE
Did the clouds that are very low on the map have been always flat?

### ISSUE THREAD

**Issue by HeroErik312** [Modding-Legacy/Aether-Legacy#231]

**Comment by HeroErik312** [comment]
![2017-12-14_18 19 44](https://user-images.githubusercontent.com/31433722/34005556-7ef5cd20-e0fb-11e7-94cc-cd935e173121.png)

**Comment by HeroErik312** [comment]
Because i have it a bit differend in the mind [Aether 1.0.0.]
![2017-12-14_14 56 49](https://user-images.githubusercontent.com/31433722/34005664-f066dfee-e0fb-11e7-9538-84e70101d34d.png)

**Comment by KingPhygieBoo** [comment]
Yes, this is intentional. The old generation cannot be added back due to cascading worldgen lag.
