### ISSUE TITLE
Is it normal that the Whirlwind throws items out of nothing? [Clay, Stick, Sand, Gravel, Oak log, Iron, Gold, Coal, Flint, Pumpkin]

### ISSUE THREAD

**Issue by HeroErik312** [Modding-Legacy/Aether-Legacy#232]
![2017-12-14_18 32 40](https://user-images.githubusercontent.com/31433722/34006034-3bae0b8e-e0fd-11e7-86b2-57410f62758a.png)
![2017-12-14_18 32 52](https://user-images.githubusercontent.com/31433722/34006055-4a187cea-e0fd-11e7-9cc5-4f15d413a7e5.png)

**Comment by 115kino** [comment]
Yes, this is indeed intentional.
