### ISSUE TITLE
Cascading World Gen console stuff

### ISSUE THREAD

**Issue by Darkmega18** [Modding-Legacy/Aether-Legacy#233]
There appears to be some cascading world gen issues going on. I get bursts of lag quite often while exploring the aether in the current 1.12.2 version. Perhaps you could look into how the generation should be done to make it stop?

**Comment by KingPhygieBoo** [comment]
This is a known issue, and has been in progress for awhile.

**Comment by Lachney** [comment]
Fixed in upcoming release :)
