### ISSUE TITLE
[1.12.2] Crash on launch

### ISSUE THREAD

**Issue by Kevun1** [Modding-Legacy/Aether-Legacy#234]
Forge v2556

Log: https://pastebin.com/F8ZWe8U5

The mod crashes on startup

**Comment by 115kino** [comment]
I put a disclaimer on the curseforge page, you need v2565 to load Aether Legacy (at this point in time that's the latest version of forge and not the recommended.

**Comment by Lachney** [comment]
Important that we fix with recommended version :)

**Comment by ItzDennisz** [comment]
fffiiiine...
