### ISSUE TITLE
Never Ending Portal Loop

### ISSUE THREAD

**Issue by Oxosorrel** [Modding-Legacy/Aether-Legacy#235]
Just tried out the new 1.12 build aether_legacy-1.12.2-1.0 and this old issue seems to be back. On a multiplayer server, I built a portal frame in creative. Went in... everything was great. On my return trip I'm stuck in an infinite loop teleporting back and forth. Leaving the game and re entering the game pulls you out at a location near bedrock below the portal frame.

Sounds very similar to an older issue that was closed. 
https://github.com/Modding-Legacy/Aether-Legacy/issues/137

**Comment by Rightfuldeathray** [comment]
and issue  [#128](https://github.com/Modding-Legacy/Aether-Legacy/issues/128)

**Comment by Lachney** [comment]
Getting this issue as well. Wasn't getting it at first in creative. Switched to survival then back to creative and am now getting annoying issue.

**Comment by 115kino** [comment]
The issue does not occur anymore with the latest versions of the hotfix. If the issue keeps on happening after the winter hotfix please feel free to re-open this issue.

**Comment by aycfes** [comment]
well, now on 1.4.3 it seems to be back, but with the nether portal

**Comment by KingPhygieBoo** [comment]
That's a vanilla issue, which is why we also have a similar issue. Also, I recommend 1.4.4, as that is the latest version now.
