### ISSUE TITLE
Cyberwares 1.10.2 GUI compatibility

### ISSUE THREAD

**Issue by Rightfuldeathray** [Modding-Legacy/Aether-Legacy#236]
if a player has the cyberwares mod, and obtains and uses fine manipulators for a 3x3 crafting in inventory, then the cloud button disappears because the 3x3 ui is a different one from the default ui, making it impossible to alter your aether inventory
issue has also been sent to cyberwares

**Comment by ItzDennisz** [comment]
I really don't see why this should be 'fixed'...

**Comment by Buttcrackofthunder** [comment]
you don't see why a bug that prevents a large part of Aether from working should be fixed?

**Comment by Darkmega18** [comment]
eat a cyclic crafting cake and save the slot for retractable claws or something, that uses a seperate button and doesn't kill the gui as far as I noticed.

**Comment by Lachney** [comment]
I don't think this seems to be an issue in later versions of this mod.
https://minecraft.curseforge.com/projects/roboticparts

Perhaps they fixed it over their side?
![img](https://i.qua.cx/ThgG5.png)

Anyway, I am going to close this issue for now and if it is still an issue or causing issues, please open a new one! Thank you for letting us now about this one.
