### ISSUE TITLE
Altar problem.

### ISSUE THREAD

**Issue by MintyFrozen** [Modding-Legacy/Aether-Legacy#241]
When I use altar I place quicksoil/blueberry e.t.c. Then I charge it with ambrosium. Ambrosium is wasting. But quicksoil is not creating quicksoil glass. So altar is not creating new items. Is there any solution?

**Comment by KingPhygieBoo** [comment]
What version is this on?

**Comment by MintyFrozen** [comment]
1.12.2

**Comment by KingPhygieBoo** [comment]
Right, I'll test that in a bit

**Comment by Lachney** [comment]
Got this myself :(

**Comment by 115kino** [comment]
Fixed on all versions of Aether Legacy in the coming hotfix.
