### ISSUE TITLE
Crash with Antique Atlas

### ISSUE THREAD

**Issue by Zsashas** [Modding-Legacy/Aether-Legacy#245]
https://github.com/AntiqueAtlasTeam/AntiqueAtlas/issues/158

**Comment by 115kino** [comment]
Can you try reproducing the crash without Aether Legacy installed?

**Comment by Zsashas** [comment]
The crash specifically happens when entering the Aether, so no.

**Comment by 115kino** [comment]
Testing at this moment, 1.11.2 doesn't seem to have this crash. Checking 1.10.2 and 1.12.2 in the following hours.

**Comment by 115kino** [comment]
Aether Legacy has no issues with AntiqueAtlas on 1.11.2 and 1.12.2

**Comment by 115kino** [comment]
A hotfix will be releasing soon. If you still find this issue is happening please feel free to open this issue again.

**Comment by Kenkron** [comment]
This crash was AA's fault, and fixed as of 4.4.9
