### ISSUE TITLE
[Request] Right-clicking on Valkyries doesn't trigger dialogue after the first time

### ISSUE THREAD

**Issue by Zsashas** [Modding-Legacy/Aether-Legacy#246]
If I'm trying to fight them with any weapon that requires right-click, I can't use it unless I get far enough away, and that's nearly impossible in the close quarters of the dungeon.

Is the option to talk while fighting really needed?

**Comment by KingPhygieBoo** [comment]
I will disable them from speaking while in combat. 👍

**Comment by KingPhygieBoo** [comment]
All fixed!
