### ISSUE TITLE
White apples don't work

### ISSUE THREAD

**Issue by JesterguyNZ** [Modding-Legacy/Aether-Legacy#247]
Two things
1. They don't cure cockatrice poison
2. This [https://cdn.discordapp.com/attachments/290392927597887489/393173085148151816/2017-12-21_11.48.53.png](url)
It lasts for a couple seconds before being able to see again.

**Comment by JonathanTheInsane** [comment]
So the cockatrice poison making you unable to see is also an issue, I would assume.

**Comment by JonathanTheInsane** [comment]
So the cockatrice poison making you unable to see is also an issue, I would assume. Also, regular milk doesn't work either, but doesn't give the green screen.

**Comment by KingPhygieBoo** [comment]
The green overlay is not an issue, neither is the purple from the Cockatrice @JonathanTheInsane

**Comment by 115kino** [comment]
Fixed in the holiday hotfix
