### ISSUE TITLE
Sun Altar crash on Multiplayer

### ISSUE THREAD

**Issue by KingPhygieBoo** [Modding-Legacy/Aether-Legacy#250]
Confirmed by another person as well, we both were able to experience this by attempting to open the Sun Altar on a server. The server did not crash, just the client.
[crash-2017-12-27_00.46.47-client.txt](https://github.com/Modding-Legacy/Aether-Legacy/files/1588491/crash-2017-12-27_00.46.47-client.txt)

**Comment by 115kino** [comment]
Fixed in the holiday hotfix!
