### ISSUE TITLE
Tile Entities don't update the client until the GUI is opened.

### ISSUE THREAD

**Issue by KingPhygieBoo** [Modding-Legacy/Aether-Legacy#251]
Example:
We have player 1 and 2; player 1 enchants some Gravitite, and can see particles, and hear the sounds the Enchanter is making. Player 2 cannot see that until they open the GUI. Once the operation has finished, the Players will still see signs of activity until the GUI is opened again. Basically I would assume a packet is needed to update the client to tell them the operation has started/finished.

(Tested with 2 people)

**Comment by 115kino** [comment]
Fixed in the holiday hotfix
