### ISSUE TITLE
Cannot create Aether Portal

### ISSUE THREAD

**Issue by mahilo3550** [Modding-Legacy/Aether-Legacy#253]
Whenever I attempt creating the portal with a (vanilla) bucket of water, it will show the portal as it should appear when created (blue screen filling the area inside of the glowstone) only momentarily and immediately vanishes once gravity begins to affect the water and it begins to spread/flow. This happens no matter which portal block I attempt to "ignite" the portal from as well as in any dimension. I'm using alpha version 1.0 of the mod for 1.12.2 w/Forge 1.12.2-14.23.1.2582 and about 100 other mods on a survival mode single player world with cheats enabled. Please help with this issue.

**Comment by 115kino** [comment]
Mahilo, did you, by chance, install Aether II with Aether Legacy? Please provide the full mod list

**Comment by mahilo3550** [comment]
No I didn't. I found out that I had to use a Skyroot Bucket of Water to create the portal (using cheats obviously, since I'd never gone to the Aether). What is the dimension ID for Aether in this mod?

**Comment by 115kino** [comment]
Dimension 4. You can customize the ID through the Aether Legacy config. That shouldn't cause the issue with portals, what were the list of mods you were using?

**Comment by TortelliniTurtle** [comment]
in the config there is an option to specificly make it so it would require a skyroot bucket
set it to false in order to allow for normal water

**Comment by KingPhygieBoo** [comment]
I've been doing a survival, and have not been able to reproduce this issue. If this happens again, feel free to reopen this issue!
