### ISSUE TITLE
Advancement issue

### ISSUE THREAD

**Issue by TortelliniTurtle** [Modding-Legacy/Aether-Legacy#262]
I am using this mod in minecraft version 1.12.2, and it seems every achievement(advancement) crashes my game

**Comment by TortelliniTurtle** [comment]
Only happens on my multiplayer server

**Comment by Darkmega18** [comment]
this also. I have a log. two of them now cause it blew up as soon as i reloaded.
[crash-2018-01-01_07.47.13-server.txt](https://github.com/Modding-Legacy/Aether-Legacy/files/1596033/crash-2018-01-01_07.47.13-server.txt)
[crash-2018-01-01_07.44.14-server.txt](https://github.com/Modding-Legacy/Aether-Legacy/files/1596034/crash-2018-01-01_07.44.14-server.txt)

**Comment by TortelliniTurtle** [comment]
for me I would get the advancement and it would be done

**Comment by TortelliniTurtle** [comment]
but unfortunitally my friends joined and it became worse of a problem

**Comment by Darkmega18** [comment]
cause every single advancement that pops means another server crash. :V I think it's cause my quest book gives multiple things that would proc an advancement. so theres like 3 or 4 of them that'd show up from picking up the items within. :V

**Comment by KingPhygieBoo** [comment]
Dupe of #259
