### ISSUE TITLE
Dangerous alternative prefixes

### ISSUE THREAD

**Issue by NotAVerb** [Modding-Legacy/Aether-Legacy#264]
v1.0.1 Forge complains about the registry.

https://gist.github.com/NotAVerb/57719310ba8e7ea306a35e4a219081a3

**Comment by Lachney** [comment]
Fixed the issue, here's another issue #295 
Fixed in commit https://github.com/Modding-Legacy/Aether-Legacy/commit/e62723595ed83cc5b55ab894e8ed3e1b00f724a2
