### ISSUE TITLE
Queen Valkyrie Not Droping Keys? 

### ISSUE THREAD

**Issue by JonMolina83** [Modding-Legacy/Aether-Legacy#265]
i have fought the queen 2 times and each time i did not get a key to open the chest. is this a bug? because i had to spawn in the key twice because of this. some one please answer this i want my loot :(

**Comment by taj1994** [comment]
Have you beaten the bronze dungeon first?

**Comment by KingPhygieBoo** [comment]
@taj1994 You wouldn't need to do that.
@JonMolina83 What version are you using? And do you have any other mods installed?

**Comment by JonMolina83** [comment]
Ive found out why they havent droped the key. because for some reason the
first time you beat her you get the achivement and for some reason when i
get it she doesent drop it the first time

**Comment by KingPhygieBoo** [comment]
I've been defeating a ton of Valkyrie Queens, I have not been able to reproduce this. If it comes up again, feel free to reopen the issue.
