### ISSUE TITLE
Valkyrie Queen Not Spawning

### ISSUE THREAD

**Issue by Nimflora** [Modding-Legacy/Aether-Legacy#266]
I've been to like 3 different silver dungeons and she's just...not there. I'm on normal mode.

**Comment by KingPhygieBoo** [comment]
I haven't been able to reproduce this issue after visiting many Silver Dungeons. If this happens again, feel free to open this issue!

**Comment by Nimflora** [comment]
Okay so I've determined the problem: once I switch my gamemode to Peaceful ONCE, turning it back to Normal will not bring the queens back in ANY DUNGEONS. That still seems like a problem..?
