### ISSUE TITLE
Dungeon reward chests don't always face away from walls

### ISSUE THREAD

**Issue by Ultimagic5** [Modding-Legacy/Aether-Legacy#269]
![2018-01-12_21 18 29](https://user-images.githubusercontent.com/25495829/34902296-4940949a-f7de-11e7-9e62-ef8b4ce2f9b8.png)
![2018-01-12_21 01 10](https://user-images.githubusercontent.com/25495829/34902263-80a19278-f7dd-11e7-87d4-b687a7396079.png)

**Comment by KingPhygieBoo** [comment]
This isn't too much of an issue for Silver Dungeons, however for Gold Dungeons yes, this is an issue.
