### ISSUE TITLE
Silver dungeon mimic chests *always* spawn together

### ISSUE THREAD

**Issue by Ultimagic5** [Modding-Legacy/Aether-Legacy#270]
Gonna go ahead and say always, because ive literally never seen two by each other where one was a regular chest and a mimic or any other variation. I can guarantee myself that if any room has two chests i shouldn't bother checking them

**Comment by KingPhygieBoo** [comment]
Yeah this is planned to be fixed soon.

**Comment by 115kino** [comment]
Fixed in recent commits
