### ISSUE TITLE
[1.12.2] Not all modded pickaxes work on the slider boss.

### ISSUE THREAD

**Issue by Spearkiller** [Modding-Legacy/Aether-Legacy#271]
Title. It's pretty random what works and what doesnt.
From the ones I've tested
Doesn't work: Draconic Pickaxe (Draconic Evolution), Tinkers Construct Pickaxes , and Red Matter Pickaxe (ProjectE).
Do work: Elementium (Botania), Star-Steel (Base Metals), and Supremium Pickaxe (Mystical crops)

Perhaps to further help this issue, add an option in the configs to whitelist certain pickaxes to work on the boss (To help with custom ones added by Quadrun/Customthings)?

Thanks :)

**Comment by ItzDennisz** [comment]
imo that's a problem with those mods cuz they're not using ItemPickaxe (which is what Aether Legacy uses to check if an item can damage the slider).
