### ISSUE TITLE
Aether slabs/stairs use opaque block lighting instead of transparent block lighting

### ISSUE THREAD

**Issue by susieqt** [Modding-Legacy/Aether-Legacy#272]
idk if im wording this right but it appears they are being counted as solid blocks unlike every vanilla slab/stair, pictures can explain better

http://puu.sh/z5NQk/98b463a528.jpg vs http://puu.sh/z5NVb/401a7d0131.jpg

these lighting bugs are consistent, any time an aether slab is next to a solid block it breaks the lighting on whichever side connects to the slab, in fact, the only way to connect aether slabs to solid blocks at all without breaking the lighting is to put stairs in-between with the bottom part of the stair touching the slab
example 1: http://puu.sh/z5O0x/47c06b3894.jpg (theres slabs underneath the floor)
example 2: http://puu.sh/z5Oh3/1c85ee434c.jpg

**Comment by 115kino** [comment]
Fixed in future v1.4.0 release and above.
