### ISSUE TITLE
Legacy v2.0 crashes when entering a world (sorry for my bad english)

### ISSUE THREAD

**Issue by 0Chris0** [Modding-Legacy/Aether-Legacy#277]
-- Head --
Thread: Server thread
Stacktrace:
at com.legacy.aether.player.PlayerAether.updatePlayerReach(PlayerAether.java:329)
at com.legacy.aether.player.PlayerAether.onUpdate(PlayerAether.java:183)
at com.legacy.aether.player.PlayerAetherEvents.onPlayerUpdate(PlayerAetherEvents.java:126)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_394_PlayerAetherEvents_onPlayerUpdate_LivingUpdateEvent.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:554)
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2082)
at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:232)

-- Player being ticked --
Details:
Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
Entity ID: 405
Entity Name: Chris1337
Entity's Exact location: -721.29, 58.74, 244.61
Entity's Block location: World: (-722,58,244), Chunk: (at 14,3,4 in -46,15; contains blocks -736,0,240 to -721,255,255), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
Entity's Momentum: 0.00, 0.00, 0.00
Entity's Passengers: []
Entity's Vehicle: ERROR NullPointerException: null
Stacktrace:
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
Connection: net.minecraft.network.NetworkManager@77df0588
Stacktrace:
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
Minecraft Version: 1.12.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 1333134224 bytes (1271 MB) / 2281701376 bytes (2176 MB) up to 3221225472 bytes (3072 MB)
JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
IntCache: cache: 8, tcache: 53, allocated: 0, tallocated: 37
FML: MCP 9.42 Powered by Forge 14.23.0.2512 Optifine OptiFine_1.12.2_HD_U_C7 31 mods loaded, 31 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

| State     | ID                | Version              | Source                                      | Signature                                |
|:--------- |:----------------- |:-------------------- |:------------------------------------------- |:---------------------------------------- |
| UCHIJAAAA | minecraft         | 1.12.2               | minecraft.jar                               | None                                     |
| UCHIJAAAA | mcp               | 9.42                 | minecraft.jar                               | None                                     |
| UCHIJAAAA | FML               | 8.0.99.99            | forge-1.12.2-14.23.0.2512.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCHIJAAAA | forge             | 14.23.0.2512         | forge-1.12.2-14.23.0.2512.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCHIJAAAA | mercurius_updater | 1.0                  | MercuriusUpdater-1.12.2.jar                 | None                                     |
| UCHIJAAAA | aether_legacy     | 1.12.2-v2.0          | aether_legacy-1.12.2-v2.0.jar               | None                                     |
| UCHIJAAAA | quark             | r1.4-122             | Quark-r1.4-122.jar                          | None                                     |
| UCHIJAAAA | autoreglib        | 1.3-15               | AutoRegLib-1.3-15.jar                       | None                                     |
| UCHIJAAAA | grimpack          | 5.2.12.78            | Grim+Pack-1.12.2-5.2.12.78.jar              | None                                     |
| UCHIJAAAA | ichunutil         | 7.1.4                | iChunUtil-1.12.2-7.1.4.jar                  | None                                     |
| UCHIJAAAA | jei               | 4.8.5.133            | jei_1.12.2-4.8.5.133.jar                    | None                                     |
| UCHIJAAAA | lycanitesmobs     | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
| UCHIJAAAA | arcticmobs        | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
| UCHIJAAAA | demonmobs         | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
| UCHIJAAAA | desertmobs        | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
| UCHIJAAAA | elementalmobs     | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
| UCHIJAAAA | forestmobs        | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
| UCHIJAAAA | freshwatermobs    | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
| UCHIJAAAA | infernomobs       | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
| UCHIJAAAA | junglemobs        | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
| UCHIJAAAA | mountainmobs      | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
| UCHIJAAAA | plainsmobs        | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
| UCHIJAAAA | saltwatermobs     | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
| UCHIJAAAA | shadowmobs        | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
| UCHIJAAAA | swampmobs         | 1.18.0.0 - MC 1.12.2 | LycanitesMobsComplete+1.18.0.0+[1.12.2].jar | None                                     |
| UCHIJAAAA | metamorph         | 1.1.4                | metamorph-1.1.4-1.12.1.jar                  | None                                     |
| UCHIJAAAA | portalgun         | 7.0.0                | PortalGun-1.12.2-7.0.1.jar                  | None                                     |
| UCHIJAAAA | primitivemobs     | 1.1.1                | Primitive-Mobs-Mod-1.12.2.jar               | None                                     |
| UCHIJAAAA | spartanweaponry   | beta 1.1.2           | SpartanWeaponry-1.12.2-beta-1.1.2.jar       | None                                     |
| UCHIJAAAA | twilightforest    | 3.1.128              | twilightforest-1.12.2-3.1.128-universal.jar | None                                     |
| UCHIJAAAA | worldedit         | 6.1.8                | worldedit-forge-mc1.12-6.1.8-dist.jar       | None                                     |

Loaded coremods (and transformers): 

LoadingPlugin (Quark-r1.4-122.jar)
vazkii.quark.base.asm.ClassTransformer
GL info: ERROR RuntimeException: No OpenGL context found in the current thread.
Grim Pack loaded parts:
= Grim Core { Loaded }
~ Enable aluminum subpart { Enabled }
~ Enable coal subpart { Enabled }
~ Enable graphite subpart { Enabled }
~ Enable iron subpart { Enabled }
~ Enable rubber subpart { Enabled }
~ Enable steel subpart { Enabled }
= Grim Cuisine { Loaded }
~ Enable SubPart chocolate { Enabled }
~ Enable SubPart dairy { Enabled }
~ Enable SubPart dragon fruit { Enabled }
~ Enable SubPart health { Enabled }
~ Enable SubPart pie { Enabled }
~ Enable SubPart soda { Enabled }
= Grim Decor { Loaded }
~ Enable SubPart alarm { Enabled }
~ Enable SubPart cages { Enabled }
~ Enable SubPart calendar { Enabled }
~ Enable SubPart colorizer { Enabled }
~ Enable SubPart decorations { Enabled }
~ Enable SubPart fireplaces { Enabled }
~ Enable SubPart flat item frame { Enabled }
~ Enable SubPart fluro { Enabled }
~ Enable SubPart frames { Enabled }
~ Enable SubPart furniture { Enabled }
~ Enable SubPart lamp posts { Enabled }
~ Enable SubPart lanterns { Enabled }
~ Enable SubPart lightbulbs { Enabled }
~ Enable SubPart neon sign { Enabled }
~ Enable SubPart slopes { Enabled }
~ Enable SubPart wall clock { Enabled }
~ Enable SubPart wallpaper { Enabled }
= Grim Industry { Loaded }
~ Enable SubPart bridges { Enabled }
~ Enable SubPart chunk loader { Enabled }
~ Enable SubPart conveyor { Enabled }
~ Enable SubPart decoration { Enabled }
~ Enable SubPart doors { Enabled }
~ Enable SubPart elemental blocks { Enabled }
~ Enable SubPart extruder { Enabled }
~ Enable SubPart fans { Enabled }
~ Enable SubPart gates { Enabled }
~ Enable SubPart gravity { Enabled }
~ Enable SubPart hlights { Enabled }
~ Enable SubPart ice maker { Enabled }
~ Enable SubPart machines { Enabled }
~ Enable SubPart metal works { Enabled }
~ Enable SubPart nuclear { Enabled }
~ Enable SubPart rways { Enabled }
~ Enable SubPart sensors { Enabled }
~ Enable SubPart shaped charges { Disabled }
~ Enable SubPart spikes { Enabled }
~ Enable SubPart steel { Enabled }
~ Enable SubPart storage { Enabled }
~ Enable SubPart torches { Enabled }
~ Enable SubPart workbench upgrades { Enabled }
= Grim Tools { Loaded }
~ Enable SubPart backpacks { Enabled }
~ Enable SubPart black diamond { Enabled }
~ Enable SubPart boomerangs { Enabled }
~ Enable SubPart buckets { Enabled }
~ Enable SubPart chicken suit { Enabled }
~ Enable SubPart chisel { Enabled }
~ Enable SubPart detonators { Enabled }
~ Enable SubPart extinguisher { Enabled }
~ Enable SubPart grenade launcher { Enabled }
~ Enable SubPart hammers { Enabled }
~ Enable SubPart knives { Enabled }
~ Enable SubPart machetes { Enabled }
~ Enable SubPart masks { Enabled }
~ Enable SubPart multitools { Enabled }
~ Enable SubPart pokeball { Enabled }
~ Enable SubPart portable workbench { Enabled }
~ Enable SubPart powerstaff { Enabled }
~ Enable SubPart ray guns { Enabled }
~ Enable SubPart slingshots { Enabled }
~ Enable SubPart spears { Enabled }
~ Enable SubPart staffs { Enabled }
~ Enable SubPart ultimate fist { Enabled }
~ Enable SubPart wands { Enabled }
= Grim Util { Loaded }
~ Enable SubPart auto item replacer { Disabled }
~ Enable SubPart auto torch { Enabled }
~ Enable SubPart chicken feathers { Enabled }
~ Enable SubPart debug { Disabled }
~ Enable SubPart double doors { Enabled }
~ Enable SubPart frozen { Enabled }
~ Enable SubPart fusrodah { Enabled }
~ Enable SubPart graves { Enabled }
~ Enable SubPart infinite lava { Disabled }
~ Enable SubPart time { Enabled }
= Grim World { Loaded }
~ Enable SubPart 8-bit mobs { Enabled }
~ Enable SubPart corruption { Disabled }
~ Enable SubPart desert wells { Enabled }
~ Enable SubPart flat bedrock { Enabled }
~ Enable SubPart floating island world type { Disabled }
~ Enable SubPart floating islands { Enabled }
~ Enable SubPart fungus { Enabled }
~ Enable SubPart glowstone seeds { Enabled }
~ Enable SubPart gunpowder reeds { Enabled }
~ Enable SubPart ice pixie { Enabled }
~ Enable SubPart more people { Disabled }
~ Enable SubPart randomite { Enabled }
~ Enable SubPart ruins { Enabled }
~ Enable SubPart treasure mobs { Enabled }
~ Enable SubPart world gen expanded { Enabled }

Profiler Position: N/A (disabled)
Player Count: 1 / 8; [EntityPlayerMP['_Chris1337_'/405, l='New World', x=-721.29, y=58.74, z=244.61]]
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'
OptiFine Version: OptiFine_1.12.2_HD_U_C7
Render Distance Chunks: 7
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.201.1151.1008
OpenGlRenderer: AMD Radeon HD 5450
OpenGlVendor: ATI Technologies Inc.
CpuCount: 2

Now I downloaded it from curse but it still crashes. It crashes when I go into a world

**Comment by KingPhygieBoo** [comment]
Update your Forge, and then try.

**Comment by ItzDennisz** [comment]
held item is null. Isnt it supposed to be ItemStack#EMPTY?

**Comment by 0Chris0** [comment]
Updating forge works
