### ISSUE TITLE
can i make the 1.7 port of the aether 

### ISSUE THREAD

**Issue by catbryce** [Modding-Legacy/Aether-Legacy#278]
it has been a long time and it is still not done. i am willing to make it if you are not going to

**Comment by KingPhygieBoo** [comment]
The 1.7.10 version started development, but will take a very long time, as we want to focus on the _quality_, rather than just porting it.

**Comment by catbryce** [comment]
ok thank you the comment on the home page made it sound like it was cancelled

**Comment by ItzDennisz** [comment]
just use sponge if the reason you want 1.7.10 is cauldron.

**Comment by catbryce** [comment]
what is sponge or cauldron?

**Comment by catbryce** [comment]
OK i looked it up i don't use plugins. the reason i want 1.7.10 aether is i like 1.7, most other mods i like have a 1.7, i like the stability that comes with not updating, i am not going to ask for the other mods to update to versions i don't even like, and finally because they told us they will there was a poll and everything.

**Comment by ItzDennisz** [comment]
someday people're just gonna have to let go of 1.7.10.

**Comment by Lachney** [comment]
@ItzDennisz too bad we cant let it go either!! we made 1.7.10 port
too bad ghost deleted their account i hope they know we are making 1.7.10
