### ISSUE TITLE
aether portal

### ISSUE THREAD

**Issue by lovique** [Modding-Legacy/Aether-Legacy#28]
the aether portal is very bugged on creative mode He teleports me constantly it's very difficult enter to the aether ! Maybe he could teleport us some farther blocks!

**Comment by DeadSix27** [comment]
I have the same issue, what he means is, if you are in creative and go through the portal, you will end up on the other end INSIDE the portal block, meaning you go back to the other end right away and it happens again, ending up in a endless loop.

**Comment by 115kino** [comment]
This bug is fixed in v1.4, no more portal teleportation issues

**Comment by BBoldt** [comment]
@115kino You should leave these bug reports open until you do a release, otherwise you will get a lot of duplicates.
