### ISSUE TITLE
[SUGGESTION] Portal Block

### ISSUE THREAD

**Issue by Okii35** [Modding-Legacy/Aether-Legacy#283]
Hello. Just a suggestion to replace the Glowstone Block by an other block (minecraft or modded block) to create the portal. Configurable in the config file.

Like that we can force the player to go in the Nether and the End and betweenland (etc) before go in Aether.

**Comment by 115kino** [comment]
The teleportation is already using an event to determine if the player can teleport or not. If mods want to disable aether teleportation for any reason they can simply cancel EntityTravelToDimemsionEvent.
