### ISSUE TITLE
missing water pools

### ISSUE THREAD

**Issue by Hypsellis** [Modding-Legacy/Aether-Legacy#286]
There is absolutely no water pools which spawn in the Aether, while they spawned in high quantity in the original mod.

**Comment by KingPhygieBoo** [comment]
Are you sure you aren’t referring to Aether II? I dont recall ponds in Aether I at all, screenshots would be helpful

**Comment by Hypsellis** [comment]
No they already existed in Aether1, and it would have more sence that water generate in Aether.

**Comment by KingPhygieBoo** [comment]
Could you give me some screenshots? To keep the mod faithful to the original, if they weren't in Aether I, they won't be added

**Comment by Hypsellis** [comment]
Is it too complicated for you to search it by yourself on google. I find a ton shit of pictures showing water pools and cascades when searching Aether1.
https://www.google.fr/search?biw=1920&bih=915&tbm=isch&sa=1&ei=LMKZWtfTJtHbwQKesriAAg&q=minecraft+aether+1&oq=minecraft+aether+1&gs_l=psy-ab.3..0i24k1l2.136892.142035.0.142362.12.12.0.0.0.0.266.1865.0j5j4.9.0....0...1c.1.64.psy-ab..4.4.859...0i7i30k1j0i8i13i30k1j0i10i24k1j0i13k1.0.5BH0DUFzQyY

**Comment by KingPhygieBoo** [comment]
All I see is Aether II, Aether I has small waterfalls that generate in the sides of islands. I know that used to be in Aether Legacy but I don't know where that is now
