### ISSUE TITLE
book of lore

### ISSUE THREAD

**Issue by lovique** [Modding-Legacy/Aether-Legacy#29]
book of lore achivement 
Is not obtainable

**Comment by TheCorruption** [comment]
Make sure you do exactly what the achievement says.

**Comment by lovique** [comment]
use the book of lore

**Comment by 115kino** [comment]
Put the book of lore in the book of lore

**Comment by 115kino** [comment]
And make sure you already achieved "Hostile Paradise"

**Comment by lovique** [comment]
ok it's good sorry
