### ISSUE TITLE
Pixelmon 2.0 mod conflict

### ISSUE THREAD

**Issue by Valkyy** [Modding-Legacy/Aether-Legacy#298]
Clicking the inventory cloud does nothing, therefore right-clicking and equipping an accessory or gloves means they cannot be removed, unless you die with keep inventory off.
![capture3](https://user-images.githubusercontent.com/18729303/38519933-5089aa64-3c0f-11e8-84f5-53eb614bebba.PNG)

**Comment by 115kino** [comment]
Fixed and tested. New release planned in the coming days.
