### ISSUE TITLE
Invisibility Cloak causing player to flash in for a frame and then out

### ISSUE THREAD

**Issue by GreatestFool** [Modding-Legacy/Aether-Legacy#305]
I had to try it out when I saw it, and I really like it. However I did notice a problem with my [hand glitching in and out of view](https://imgur.com/a/e784VbH), and in[ third person the body does as well.](https://imgur.com/a/qhBm8x6)

Not sure how you'd go to fix the third person thing. But the first person view can be fixed simply by showing the hand like normal. (Or fixing the glitchy behavior somehow, I prefer not seeing the hand actually)

**Comment by Lachney** [comment]
@GreatestFool Does this still happen with the latest version of Aether Legacy also what extra mods are you running with it? ^^
