### ISSUE TITLE
Crash on loading

### ISSUE THREAD

**Issue by DWX12** [Modding-Legacy/Aether-Legacy#310]
**Aether Legacy Version(s) Affected**:
Aether Legacy v3.0

**Forge version**: 
14.23.3.2702

**Extra Mods**: 
Available in crash report.

**Issue:**
Crash upon loading caused by duplicate ID.

**How to reproduce:**
Attempt to start up minecraft with custom modpack.

**Crash log:**
https://hastebin.com/izucexecef.bash

**Comment by Lachney** [comment]
It's been a while, unfortunately that log is gone but if you need to change biome and dimension IDs that is possible in the AetherI.cfg file. Reopen this issue, if you are still getting problems. ^-^
