### ISSUE TITLE
ClassCastException when encountering Swet

### ISSUE THREAD

**Issue by SargeRyong** [Modding-Legacy/Aether-Legacy#311]
**Aether Legacy Version(s) Affected**: 1.12.1-v3.0

**Forge version**: 14.23.4.2705

**Extra Mods**: Many.  However, crash appears to be internal to Aether Legacy code.

**Issue:** Works as expected until a player loads a chunk that contains a Swet, at which point the player's client crashes.

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
      at com.legacy.aether.entities.passive.mountable.EntitySwet.isFriendly(EntitySwet.java:623)
(see below for full crash log)

**How to reproduce:** See above.

**Crash log:** https://paste.dimdev.org/zanasurihu.mccrash

**Comment by SargeRyong** [comment]
Not quite sure how this is happening, since I can clearly see that isFriendly does in fact return a bool.

**Comment by SargeRyong** [comment]
Attempted to recreate the issue myself and was unable to.  Other swets seem fine.  Not sure how my player managed to provoke this one.

**Comment by iamtpage** [comment]
I am also experiencing this issue with players on my server, same error, and same reproducible steps.

**Comment by KingPhygieBoo** [comment]
This seems to happen with naturally spawning Swets, we will look into it.

**Comment by 115kino** [comment]
Fixed in the future v1.4.0 release.
