### ISSUE TITLE
[1.12.2] Valkyrie Wings has a weird outline when wearing a full set of Valkyrie Armor + Gloves.

### ISSUE THREAD

**Issue by Z-Tunic** [Modding-Legacy/Aether-Legacy#314]
Minecraft: 1.12.2
Forge: 14.23.4.2708

Mods:
aether_legacy-1.12.2-v3.0

---

Image:
![](https://cdn.discordapp.com/attachments/377171551155650560/458026278071828489/valkyriewingglitch.PNG)

When wearing a full set of Valkyrie Armor + Gloves... you get these Valkyrie Wings, however... they have this weird static-like outline that surrounds the wings. This outline doesn't show when viewing your inventory and it doesn't appear to show for the Valkyrie Mobs.

**Comment by Darkmega18** [comment]
feels like a transparency issue or a render bug. probably the latter. :V I got this too. I got optifine on my side.

**Comment by Z-Tunic** [comment]
This issue still occurs in "aether_legacy-1.12.2-v1.4.0". Just wondering if it's on the radar or something.

**Comment by KingPhygieBoo** [comment]
Fixed, this will be in the next update!
