### ISSUE TITLE
[1.12.2 v3] Crash with HammerCore 1.9.9.16+

### ISSUE THREAD

**Issue by Rikshy** [Modding-Legacy/Aether-Legacy#315]
**Aether Legacy Version(s) Affected**:
1.12.2 v.3.0

**Forge version**: 
14.23.4.2707

**Extra Mods**: 
HammerCore 1.9.9.16

**Issue:**
Crash on world load

**How to reproduce:**
install mods, load a world

**Crash log:**
https://paste.dimdev.org/onahevuxet.mccrash

**link to hammercore gilab issue**
#https://gitlab.com/Zeitheron/HammerCore/issues/61

**Comment by Lachney** [comment]
Looks to me like an issue with Aether II and not Aether Legacy. Sorry to make you travel from issue tracker to issue tracker but try them!
https://git.gildedgames.com/GildedGames/Aether-II

**Comment by Rikshy** [comment]
oh wow, this is absolutly my fault, im an idiot, somehow i thought its aether legacy cuz it was only written "aether" in the crash, now i remember yours would be "aether_legacy".

sorry for bothering!
