### ISSUE TITLE
GUI Conflict with FastCraftingMod

### ISSUE THREAD

**Issue by ExcitedName** [Modding-Legacy/Aether-Legacy#320]
**Aether Legacy Version(s) Affected**:
1.12.2

**Forge version**: 
14.23.2.2611

**Extra Mods**: 
FastCraftingMod

**Issue:**
The mod alters the player inventory in survival and causes the cloud button to disappear. 
Simply requesting a hotkey in case the mod author does not continue dev. 

**How to reproduce:**

**Crash log:**

**Comment by 115kino** [comment]
Fixed and tested. New release planned in the coming days.
