### ISSUE TITLE
Aether has got night time without killing sun god. +EnderZoo problem

### ISSUE THREAD

**Issue by EnderT5** [Modding-Legacy/Aether-Legacy#321]
**Aether Legacy Version(s) Affected**: 3.0 (Game version: 1.12.2) (USING SERVER)

**Forge version**: 14.23.4.2709 (SERVER)

**Extra Mods**: enderiointegrationforestry@5.0.26,tesla@1.0.63,simplyjetpacks@2.2.7.45,openmods@0.11.5,jei@4.10.0.198,dynamiclights_theplayer@1.1.3,dynamiclights_floodlights@1.0.3,cofhcore@4.5.2,draconicevolution@2.3.11,bibliocraft@2.4.4,dynamiclights@1.4.9,projecte@1.12-PE1.3.0,thermalfoundation@2.5.0,wawla@2.5.257,endercore@1.12.2-0.5.31,mcp@9.42,ctm@MC1.12-0.3.0.15,journeymap@1.12.2-5.5.2,enderiointegrationticlate@5.0.26,chameleon@1.12-4.1.3,bookshelf@2.3.552,inventorytweaks@1.63+release.109.220f184,xreliquary@1.12.2-1.3.4.767,llibrary@1.7.14,cofhworld@1.2.0,darkutils@1.8.207,betterbuilderswands@0.11.1,dynamiclights_otherplayers@1.0.9,waila@1.8.26,props@2.6.0,enderioconduitsrefinedstorage@5.0.26,guideapi@1.12-2.1.5-60,endercompass@1.2.6.1,jeresources@0.8.5.27,thermalsolars@1.12.2 V1.9,immersivepetroleum@1.1.9,forge@14.23.4.2709,quickleafdecay@1.2.4,nmsot@1.2.2-mc1.12.2,enderioconduits@5.0.26,twilightforest@3.7.424,brandonscore@2.4.2,immersivetech@1.3.10,cyclicmagic@1.15.12,ironchest@1.12.2-7.0.40.824,openblocks@1.7.6,enderzoo@1.12.1-1.4.0.49,zerocore@1.12-0.1.2.2,minecraft@1.12.2,tconstruct@1.12.2-2.10.1.87,tinkertoolleveling@1.12.2-1.0.5.DEV.30c7957,ptrmodellib@1.0.2,mousetweaks@2.8,dynamiclights_entityclasses@1.0.1,enderiomachines@5.0.26,immersiveengineering@0.12-82,baubles@1.5.2,redstoneflux@2.0.2,openmodscore@0.11.5,dynamiclights_dropitems@1.1.0,enderiopowertools@5.0.26,customspawner@3.11.4,dynamiclights_mobequipment@1.1.0,dynamiclights_flamearrows@1.0.1,enderio@5.0.26,extrautils2@1.0,roguelike@1.8.0,mocreatures@12.0.4,quark@r1.4-125,mantle@1.12-1.3.2.24,randomthings@4.1.8,autoreglib@1.3-18,oreexcavation@1.4.119,storagedrawers@1.12-5.3.5,natura@1.12.2-4.3.2.49,FML@8.0.99.99,enderiobase@5.0.26,enderiointegrationtic@5.0.26,enderioconduitsappliedenergistics@5.0.26,minecolonies@1.12.2-0.8.7582,norecipebook@1.2.1,appleskin@1.0.9,chisel@MC1.12.2-0.2.0.31,enderioconduitsopencomputers@5.0.26,bigreactors@1.12.2-0.4.5.49,recipehandler@0.10,aether_legacy@1.12.2-v3.0,dynamiclights_onfire@1.0.7,dynamiclights_creepers@1.0.6,codechickenlib@3.1.9.344,wailaharvestability@1.1.12,defaultoptions@9.2.7

**Issue:** (PLAYING IN SERVER) Aether has got night time without killing sun god. +If you have EnderZoo mod, Aether will be filled with EnderZoo monsters.

**How to reproduce:** Aether shouldn't have night time without killing sun god, like in the original Aether 1 mod and EnderZoo monsters shouldn't spawn in the Aether at night.

**Crash log:** No crash but it is still a problem.

**Comment by ItzDennisz** [comment]
that enderzoo thingy looks like a problem with enderzoo.

**Comment by KingPhygieBoo** [comment]
The night time thing was removed due to serverside issues, and as Dennis said, that is an EnderZoo problem, not ours.
