### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Sunconure11** [Modding-Legacy/Aether-Legacy#324]
**Aether Legacy Version(s) Affected**:

Aether Legacy v3.1

**Forge version**: 

14.23.4.2739

**Extra Mods**: 

Too many to list, I found this while scoping out another mod.

**Issue:**

Aether Legacy causes the game to crash

**How to reproduce:**

Boot up MC with Aether Legacy

**Crash log:**

https://pastebin.com/ak2ZVFt9

**Comment by KingPhygieBoo** [comment]
This isn't an issue with us, this is an issue with the Aether Legacy addon, they developer has been contacted and they will fix it soon.
