### ISSUE TITLE
Aether version 3.1 Crashed upon loading

### ISSUE THREAD

**Issue by UnlimatedStone9** [Modding-Legacy/Aether-Legacy#326]
The mod works fine for version 3.0 so its a 3.1 error only

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (elulib-0.1.12.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.12_mc1.12.2.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.10-core.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  CreativePatchingLoader (CreativeCore_v1.9.22_mc1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-84.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 7/24/18 8:11 PM
Description: Initializing game

java.lang.NoClassDefFoundError: Lcom/legacy/aether/CommonProxy;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredField(Class.java:2068)
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:70)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:601)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:226)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.legacy.aether.CommonProxy
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredField(Class.java:2068)
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:70)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:601)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:226)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 802296360 bytes (765 MB) / 1355808768 bytes (1293 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2739 93 mods loaded, 93 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                           | Version                         | Source                                          | Signature                                |
	|:----- |:-------------------------------------------- |:------------------------------- |:----------------------------------------------- |:---------------------------------------- |
	| UC    | minecraft                                    | 1.12.2                          | minecraft.jar                                   | None                                     |
	| UC    | mcp                                          | 9.42                            | minecraft.jar                                   | None                                     |
	| UC    | FML                                          | 8.0.99.99                       | forge-1.12.2-14.23.4.2739.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge                                        | 14.23.4.2739                    | forge-1.12.2-14.23.4.2739.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | creativecoredummy                            | 1.0.0                           | minecraft.jar                                   | None                                     |
	| UC    | itemphysic                                   | 1.4.0                           | minecraft.jar                                   | None                                     |
	| UC    | com.elytradev.movingworld.common.asm.coremod |                                 | minecraft.jar                                   | None                                     |
	| UC    | foamfixcore                                  | 7.7.4                           | minecraft.jar                                   | None                                     |
	| UC    | elucore                                      | 1.0                             | minecraft.jar                                   | None                                     |
	| UC    | aether_legacy                                | 1.12.2-v3.1                     | aether_legacy-v3.1.jar                          | None                                     |
	| U     | aether_legacy_addon                          | 1.12.2-v1.0                     | aether_legacy_addon_1.12.2-v1.0.jar             | None                                     |
	| U     | architecturecraft                            | @VERSION@                       | architecturecraft-1.12-2.68.jar                 | None                                     |
	| U     | astikoor                                     | 1.0.0                           | astikoor-1.0.0.jar                              | None                                     |
	| U     | betterbuilderswands                          | 0.11.1                          | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| U     | betterfoliage                                | 2.1.10                          | BetterFoliage-MC1.12-2.1.10.jar                 | None                                     |
	| U     | blockcraftery                                | 0.1.3                           | blockcraftery-0.1.3.jar                         | None                                     |
	| U     | charset                                      | 0.5.2.3                         | Charset-Lib-0.5.2.3.jar                         | None                                     |
	| U     | jei                                          | 4.11.0.202                      | jei_1.12.2-4.11.0.202.jar                       | None                                     |
	| U     | blockdrops                                   | 1.4.0                           | blockdrops-1.12.2-1.4.0.jar                     | None                                     |
	| U     | guideapi                                     | 1.12-2.1.6-61                   | Guide-API-1.12-2.1.6-61.jar                     | None                                     |
	| U     | bloodmagic                                   | 1.12.2-2.3.1-99                 | BloodMagic-1.12.2-2.3.1-99.jar                  | None                                     |
	| U     | bloodmoon                                    | 1.5.3                           | Bloodmoon-MC1.12.2-1.5.3.jar                    | None                                     |
	| U     | buildcraftlib                                | 7.99.17                         | buildcraft-7.99.17.jar                          | None                                     |
	| U     | buildcraftcore                               | 7.99.17                         | buildcraft-7.99.17.jar                          | None                                     |
	| U     | buildcraftbuilders                           | 7.99.17                         | buildcraft-7.99.17.jar                          | None                                     |
	| U     | buildcraftenergy                             | 7.99.17                         | buildcraft-7.99.17.jar                          | None                                     |
	| U     | buildcraftfactory                            | 7.99.17                         | buildcraft-7.99.17.jar                          | None                                     |
	| U     | buildcraftrobotics                           | 7.99.17                         | buildcraft-7.99.17.jar                          | None                                     |
	| U     | buildcrafttransport                          | 7.99.17                         | buildcraft-7.99.17.jar                          | None                                     |
	| U     | buildcraftsilicon                            | 7.99.17                         | buildcraft-7.99.17.jar                          | None                                     |
	| U     | chesttransporter                             | 2.8.8                           | ChestTransporter-1.12.2-2.8.8.jar               | None                                     |
	| U     | ctm                                          | MC1.12.2-0.3.2.18               | CTM-MC1.12.2-0.3.2.18.jar                       | None                                     |
	| U     | chisel                                       | MC1.12.2-0.2.0.31               | Chisel-MC1.12.2-0.2.0.31.jar                    | None                                     |
	| U     | chiselsandbits                               | 14.20                           | chiselsandbits-14.20.jar                        | None                                     |
	| U     | codechickenlib                               | 3.2.0.345                       | CodeChickenLib-1.12.2-3.2.0.345-universal.jar   | None                                     |
	| U     | cookingforblockheads                         | 6.4.40                          | CookingForBlockheads_1.12.2-6.4.40.jar          | None                                     |
	| U     | creativecore                                 | 1.9.9                           | CreativeCore_v1.9.22_mc1.12.2.jar               | None                                     |
	| U     | cxlibrary                                    | 1.6.1                           | cxlibrary-1.12.1-1.6.1.jar                      | None                                     |
	| U     | cyclopscore                                  | 0.11.8                          | CyclopsCore-1.12.2-0.11.8.jar                   | None                                     |
	| U     | movingworld                                  | 1.12-6.342                      | movingworld-1.12-6.342-full.jar                 | None                                     |
	| U     | davincisvessels                              | @DVESSELSVER@                   | davincisvessels-1.12-6.340-full.jar             | None                                     |
	| U     | evilcraft                                    | 0.10.61                         | EvilCraft-1.12.2-0.10.61.jar                    | None                                     |
	| U     | mantle                                       | 1.12-1.3.2.24                   | Mantle-1.12-1.3.2.24.jar                        | None                                     |
	| U     | natura                                       | 1.12.2-4.3.2.49                 | natura-1.12.2-4.3.2.49.jar                      | None                                     |
	| U     | forestry                                     | 5.8.1.322                       | forestry_1.12.2-5.8.1.322.jar                   | None                                     |
	| U     | evilcraftcompat                              | 1.0.0                           | EvilCraft-1.12.2-0.10.61.jar                    | None                                     |
	| U     | exnihilocreatio                              | 1.12-0.2.4                      | exnihilocreatio-1.12-0.2.4.jar                  | None                                     |
	| U     | excompressum                                 | 3.0.22                          | ExCompressum_1.12.2-3.0.22.jar                  | None                                     |
	| U     | tconstruct                                   | 1.12.2-2.10.1.87                | TConstruct-1.12.2-2.10.1.87.jar                 | None                                     |
	| U     | extrautils2                                  | 1.0                             | extrautils2-1.12-1.8.1.jar                      | None                                     |
	| U     | fastleafdecay                                | v14                             | FastLeafDecay-v14.jar                           | None                                     |
	| U     | foamfix                                      | 0.9.9.1-1.12.2                  | foamfix-0.9.9.1-1.12.2-anarchy.jar              | None                                     |
	| U     | foragecraft                                  | 1.14.2                          | foragecraft-1.14.2.jar                          | None                                     |
	| U     | forgelin                                     | 1.7.4                           | Forgelin-1.7.4.jar                              | None                                     |
	| U     | cfm                                          | 5.3.1                           | furniture-5.3.1-1.12.2.jar                      | None                                     |
	| U     | limelib                                      | 1.7.12                          | limelib-1.12.2-1.7.12.jar                       | None                                     |
	| U     | furnus                                       | 2.1.6                           | furnus-1.12.2-2.1.6.jar                         | None                                     |
	| U     | gogskybox                                    | 1.1-3                           | GoGSkybox 1.1-3.jar                             | None                                     |
	| U     | horsepower                                   | 2.6.1                           | HorsePower-1.12.2-2.6.1.67.jar                  | None                                     |
	| U     | mcjtylib_ng                                  | 3.0.3                           | mcjtylib-1.12-3.0.3.jar                         | None                                     |
	| U     | immcraft                                     | 1.5.0                           | immcraft-1.12-1.5.0.jar                         | None                                     |
	| U     | immersiveengineering                         | 0.12-84                         | ImmersiveEngineering-0.12-84.jar                | None                                     |
	| U     | immersivepetroleum                           | 1.1.9                           | immersivepetroleum-1.12.2-1.1.9.jar             | None                                     |
	| U     | immersivetech                                | 1.3.10                          | immersivetech-1.12-1.3.10.jar                   | None                                     |
	| U     | jarm                                         | 1.1.1                           | Just A Raft Mod-1.1.1.jar                       | None                                     |
	| U     | kjlib                                        | 1.0.4                           | kjlib-1.0.4.jar                                 | None                                     |
	| U     | metalchests                                  | v1.2.2.g3d3d54b                 | MetalChests-v1.2.2.g3d3d54b.jar                 | None                                     |
	| U     | morefurnaces                                 | 1.10.5                          | MoreFurnaces-1.12.2-1.10.5.jar                  | None                                     |
	| U     | mousetweaks                                  | 2.8                             | MouseTweaks-2.8-mc1.12.1.jar                    | None                                     |
	| U     | multipagechest                               | 1.9.1                           | MultiPageChest-1.12-1.9.1.jar                   | None                                     |
	| U     | naturescompass                               | 1.5.1                           | NaturesCompass-1.12.2-1.5.1.jar                 | None                                     |
	| U     | netherchest                                  | 0.2.3                           | netherchest-0.2.3.jar                           | None                                     |
	| U     | nex                                          | 2.1.14.15                       | NetherEx-1.12-2.1.14.15.jar                     | None                                     |
	| U     | netherportalfix                              | 5.3.13                          | NetherPortalFix_1.12.1-5.3.13.jar               | None                                     |
	| U     | recipehandler                                | 0.11                            | NoMoreRecipeConflict-0.11(1.12.2).jar           | None                                     |
	| U     | nei                                          | 2.4.1                           | NotEnoughItems-1.12.2-2.4.1.233-universal.jar   | None                                     |
	| U     | harvestcraft                                 | 1.12.2u                         | Pam's HarvestCraft 1.12.2u.jar                  | None                                     |
	| U     | primitivetools                               | 1.1.5                           | PrimitiveTools-1.12-1.1.5.jar                   | None                                     |
	| U     | woodenshears                                 | @MAJOR@.@MINOR@.@REVIS@.@BUILD@ | SBM-WoodenShears-1.12-0.0.1b8.jar               | None                                     |
	| U     | stonechests                                  | 1.0.0                           | stonechests-1.0.0.jar                           | None                                     |
	| U     | beneath                                      | 1.4.2                           | The Beneath-1.12.2-1.4.2.jar                    | None                                     |
	| U     | thebetweenlands                              | 3.3.10                          | TheBetweenlands-3.3.10-universal.jar            | None                                     |
	| U     | tinkersaether                                | 1.1.5                           | tinkersaether-1.1.5.jar                         | None                                     |
	| U     | tcomplement                                  | ${version}                      | TinkersComplement-1.12.2-0.2.3b.jar             | None                                     |
	| U     | tinkersjei                                   | 1.0                             | tinkersjei-1.0.jar                              | None                                     |
	| U     | tinkertoolleveling                           | 1.12.2-1.0.5.DEV.30c7957        | TinkerToolLeveling-1.12.2-1.0.5.jar             | None                                     |
	| U     | twilightforest                               | 3.7.424                         | twilightforest-1.12.2-3.7.424-universal.jar     | None                                     |
	| U     | unlimitedchiselworks                         | 0.2.0                           | UnlimitedChiselWorks-0.2.0.jar                  | None                                     |
	| U     | vimmersion                                   | 2.0.3.3                         | vanilla-immersion-1.12.2-2.0.3.3.jar            | None                                     |
	| U     | xaerominimap                                 | 1.15.3                          | Xaeros_Minimap_1.15.3_Forge_1.12.jar            | None                                     |
	| U     | elulib                                       | 0.1.12                          | elulib-0.1.12.jar                               | None                                     |
	| U     | moofluids                                    | 1.12.2-1.7.11.02a               | MooFluids-1.12.2-1.7.11.02a.jar                 | None                                     |
	| U     | primal_tech                                  | 0.3.3                           | PrimalTech-0.3.3.jar                            | None                                     |

	Loaded coremods (and transformers): 
FMLPlugin (elulib-0.1.12.jar)
  elucent.elulib.asm.ASMTransformer
ForgelinPlugin (Forgelin-1.7.4.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
ItemPatchingLoader (ItemPhysic_Full_1.4.12_mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.10-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
CreativePatchingLoader (CreativeCore_v1.9.22_mc1.12.2.jar)
  
IELoadingPlugin (ImmersiveEngineering-core-0.12-84.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4550' Renderer: 'Intel(R) HD Graphics 620'
	Launched Version: forge-14.23.4.2739
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 620 GL version 4.4.0 - Build 21.20.16.4550, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz

**Comment by Shnupbups** [comment]
Aether Legacy 3.1 was built from the 'Universal' branch, and as such has major refactors under the hood. This might have been accidental on Modding Legacy's part?

Aether Legacy Addon, aka 'An Addon for that Sky Dimension Mod' has not been updated to support it.

You will need to disable it, or downgrade Aether Legacy to 3.0, until further notice.

**Comment by Lachney** [comment]
Yeah this was an issue with "AN Addon for that Sky Dimension"... I am not sure if this happens in Aether Legacy v3.2 release, however if it does the mod author will have to update addon mod. Please reopen this if youre still getting an issue. ^^

**Comment by UnlimatedStone9** [comment]
I completely forgot about this issue entirely, No reason for it to stay open anyways
