### ISSUE TITLE
NullPointException Crash. Crashlog points to aether legacy

### ISSUE THREAD

**Issue by Convergence2738** [Modding-Legacy/Aether-Legacy#330]
**Aether Legacy Version(s) Affected**: 3.2

**Forge version**: 14.23.4.2745

**Extra Mods**: Another Aether Legacy Addon (one that adds skyroot doors and stuff) Aether's Tinker

**Issue:** NullpointerException Error Crash (as noted in crashlog) 

**How to reproduce:** Walk around world. You get a massive desync problem and you hang and crash on save and quit.

**Crash log:**
[crash-2018-07-24_09.15.07-client.txt](https://github.com/Modding-Legacy/Aether-Legacy/files/2250231/crash-2018-07-24_09.15.07-client.txt)

**Comment by Convergence2738** [comment]
kk. I am throwing down an update. I think it has to do with forge. The new forge updates are wonky and make some serious desync lag on their own. But they just don't like aether legacy at all and make a nullpointerexcpetion crash. If you want to play without problems, use 2740, it's stable.

**Comment by jredfox** [comment]
there are alot of coremods here I think the issue is caused by one of them remove them then try and do this

**Comment by Lachney** [comment]
Duplicate #326
