### ISSUE TITLE
Lag in player update

### ISSUE THREAD

**Issue by LemADEC** [Modding-Legacy/Aether-Legacy#333]
**Aether Legacy Version(s) Affected**: aether_legacy-1.12.2-v3.2.jar

**Forge version**: 1.12.2-14.23.4.2749

**Extra Mods**: 
n/a

**Issue:**
From profiling, it appears ASM is done systematically for each players every tick instead of caching the results.
ReflectionHelper shall be called only once per game start.

**How to reproduce:**
Code review

**Crash log:**
![image](https://user-images.githubusercontent.com/4776032/43996579-fa3468ca-9dc5-11e8-8bea-b9a7126aa8e1.png)

**Comment by 115kino** [comment]
Fixed and tested. New release planned in the coming days.
