### ISSUE TITLE
Slider can't be attacked by mod pickaxes like Tinkers | Slider sometimes invisible for other players

### ISSUE THREAD

**Issue by TheRealDadbeard** [Modding-Legacy/Aether-Legacy#335]
**Aether Legacy Version(s) Affected**:
3.2

**Forge version**: 
2749

**Extra Mods**: 
https://pastebin.com/rM1KN8pZ

**Issue:**
Title.

**Comment by KingPhygieBoo** [comment]
The Tinker's issue has been fixed and will be in the next update, as for the Slider, your friends can just relog and that isn't an issue.

PS: i renamed this as the suffocation bug is on another issue.
