### ISSUE TITLE
AerWhales randomly despawn

### ISSUE THREAD

**Issue by jredfox** [Modding-Legacy/Aether-Legacy#341]
Aether Legacy Version(s) Affected:
aether_legacy-1.12.2-v3.2

Forge version:
1.12.2-forge1.12.2-14.23.4.2732

Extra Mods:
jurassicraft

Issue:
Aerwhales despawn in like 10s

How to reproduce:
look at the whale 

Crash log:
none

**Comment by KingPhygieBoo** [comment]
They despawn when out of range of the player, or when they get stuck. This is not an issue.

**Comment by jredfox** [comment]
no they spawn directly in front of you same for alot of the mobs you made a crappy port I am tempted to make my own port

**Comment by Lachney** [comment]
> no they spawn directly in front of you same for alot of the mobs you made a crappy port I am tempted to make my own port

Unfortunately only Modding Legacy has the proper permissions to create a port, however if you believe this is still an issue, please help us out by forking the repo and creating a pull request! Also, reopen this issue to create a new one relating to Aerwhale's AI that definitely needs to be reworked.

**Comment by jredfox** [comment]
according to mojang eula I have the ability to redistrubite adapt and modify minecraft content without permission since you have to agree to their terms of service.

**Comment by Lachney** [comment]
> according to mojang eula I have the ability to redistrubite adapt and modify minecraft content without permission since you have to agree to their terms of service.

Yes sure, however content created by other mod authors is still licensed, in which the original Aether mod. We were given permission by the original team behind the mod as it was written here:

![Email](https://media.forgecdn.net/attachments/150/274/ftj1nhq.png)

I would still highly recommend forking the repo and helping contribute.

Anyways, if you aren't happy with Aether Legacy with modern versions, feel free to play the original versions or try out [Aether II](https://minecraft.curseforge.com/projects/the-aether-ii). We're not professionals, we're just dudes that love to mod Minecraft.
