### ISSUE TITLE
Zephar Config Option

### ISSUE THREAD

**Issue by jredfox** [Modding-Legacy/Aether-Legacy#342]
Aether Legacy Version(s) Affected:
aether_legacy-1.12.2-v3.2

Forge version:
1.12.2-forge1.12.2-14.23.4.2732

Extra Mods:
jurassicraft

Issue:
I remember hearing that you were going to work on fixing the zephar spawns I don't see them anywhere and they are not near as anoying as they use to be

I think there should be two separate entities and based on that will determine which one spawns and how much. One is the current the other is the mc 1.2.5 version. The aether team said you were working on this. Well just putting it hear as a reminder since it's been a while

**Comment by KingPhygieBoo** [comment]
What are you referring, to? The spawning being too low? Because in that case, they spawn quite enough. If you mean the old models, those can be enabled in the config if you so please.

**Comment by jredfox** [comment]
you really don't care you made a crappy port of the aether do you? The other zepher forms and the original config opitons

**Comment by Lachney** [comment]
Haha, I find this issue amusing, as it is wondering why the Zephyr's aren't as annoying! Who would want to be annoyed? Anyways, if you want to use the older models of Zephyr's you can change that in the config.

Enable legacy visuals!
```
misc {
    B:"Enable Legacy Visuals"=true
}
```
