### ISSUE TITLE
The GUI doesn't show up correct

### ISSUE THREAD

**Issue by qq512065439** [Modding-Legacy/Aether-Legacy#344]
**Aether Legacy Version(s) Affected**:1.12.2-1.0.10

**Forge version**:14.23.4.2758 

**Extra Mods**: ToughAsNails-1.12.2-3.1.0.115

**Issue:The GUI can't show up correct

**How to reproduce:just install ToughAsNail and enter the Aether world

**Crash log:did't crash,game still can work

**Comment by KingPhygieBoo** [comment]
What do you mean GUI? What GUI? The accessories menu, or something from ToughAsNails?

**Comment by 115kino** [comment]
Fixed and tested. New release planned in the coming days.
