### ISSUE TITLE
Aercloud textures appear washed out.

### ISSUE THREAD

**Issue by Vidarval** [Modding-Legacy/Aether-Legacy#347]
**Aether Legacy Version(s) Affected**: v3.2 for 1.12.2

**Forge version**: Recommended v14.23.4.2705 for 1.12.2

**Extra Mods**: Only Forge and Aether Legacy installed.

**Issue:** Aercloud textures appear washed out.

Blue and golden aercloud, at the moment, use tinted cold aercloud texture, instead of the available textures, which makes them look washed out both when placed down and when held in hand. In certain angles top sides of those blocks are almost completely white and desaturated.
I am not sure if this is intended or not but I couldn't find any info about it.
I provided comparison pictures by editing aercloud .json files to use the provided official aercloud textures that are found in "textures/blocks" folder.

This is how they look at the moment:

![2018-09-03_20 25 27](https://user-images.githubusercontent.com/42945508/44998992-56cf3c80-afba-11e8-9662-4b4c65216550.png)
![2018-09-03_20 25 24](https://user-images.githubusercontent.com/42945508/44998995-5a62c380-afba-11e8-9f5b-e67978c78700.png)

And this is how they look after editing .json files to use the provided textures (They used to look like this in older Aether mod versions):

![2018-09-03_20 26 37](https://user-images.githubusercontent.com/42945508/44999008-78c8bf00-afba-11e8-9eb6-ade0d0ecdd37.png)
![2018-09-03_20 26 36](https://user-images.githubusercontent.com/42945508/44999014-7d8d7300-afba-11e8-93cc-e6162bfaf813.png)

**Comment by KingPhygieBoo** [comment]
These were colored to match the 1.7.3b versions, as the more saturated ones were added later in 1.2.5. I will add a config option to satisfy this though. Thanks for the suggestion!
