### ISSUE TITLE
[1.12.2] Life Shards cannot be used/or are limited if you have other health modifiers.

### ISSUE THREAD

**Issue by Z-Tunic** [Modding-Legacy/Aether-Legacy#348]
Minecraft: 1.12.2
Forge: 14.23.4.2756

Mods:
aether_legacy-1.12.2-v3.2
AppleCore-mc1.12.2-3.1.3
AppleSkin-mc1.12-1.0.9
Baubles-1.12-1.5.2
Botania+r1.10-356
ScalingHealth-1.12.2-1.3.28-129
Cyclic-1.12.2-1.17.1
SilentLib-1.12.2-3.0.4-150
solcarrot-1.12.2-1.3.3

-----

If you have certain other mods added that allows you to increase your health by their means, you will be unable to use the Life Shards from Aether Legacy to increase your health as it'll tell you upon trying to use a shard...

"You can only use a total of 10 life shards."

...yet no shards were used.

Some of the modifiers I'm aware of are...

1. Botania
There's a item called "Ring of Odin" that increases your max health by 20 (10 Hearts).

2. Cyclic
You can increase health by using Heart Containers that you either find in chests or create them via crafting.

3. Scaling Health's
A mod that allows you to increase health with the use of Heart Containers that you can craft with shards that are dropped by mobs, by mining special ores... or XP Level Ups as well as alter damage taken via difficulty configs.

4. Spice of Life: Carrot Edition
You can increase your health by eating different types of foods. aka you are rewarded for creating & eating all types of food-like items.

-----
In these screenshots with these mods added...

aether_legacy-1.12.2-v3.2
Baubles-1.12-1.5.2
Botania+r1.10-356

![](https://cdn.discordapp.com/attachments/377171551155650560/488632926171561984/healthringofodinlessmods.PNG)
I am wearing the "Ring of Odin" from Botania which increases my max health by 20 (10 Hearts), when I attempt to use the Aether Legacy Life Shards... it tells me that I can't use them due to already using 10 so my health is capped at 40 health (20 hearts).

![](https://cdn.discordapp.com/attachments/377171551155650560/488632985910902794/healthshardsfirst.PNG)
If I use the Aether Legacy Life Shards first and then wear the Ring of Odin... it works as intended, having 60 health (30 hearts).

I think Life Shards check the player's total health which is perhaps why no Life Shards can be used if the player's health was increased by other means. If you use the Life Shards first and then increase your health by other means then the other health modifiers will stack without any issue.

**Comment by 115kino** [comment]
Fixed and tested. New release planned in the coming days.
