### ISSUE TITLE
Morph Mod Mess-up

### ISSUE THREAD

**Issue by Amborg22** [Modding-Legacy/Aether-Legacy#349]
**Aether Legacy Version(s) Affected**: 1.12.2 v2.0
**Forge version**: 1.12.2-14.2.3.4.2705
**Extra Mods**:
-Davinscis Vessels
-Gargoyles Mod
-Gravestone Mod
-NEI
-JEI
-Morph
-Tinkers Consrtuct
-Thermal Expansion
-Thermal Dynamics
-Thermal Foundation
-Tinker's Aether
-Twilight Forest
-Xaero's Minimap
**Issue:**
The affected mods include Aether Legacy and Morph. I was trying to morph back into myself at the same time I got into a swet. At that moment, my whole game froze and then crashed. Anytime I tried to log back into the world, I would end up freezing Minecraft and would have to exit. The only solution I found was to get rid of morph mod permanently. I tried adding it back in after I played it a little w/out morph, but when I added morph mod again, the exact same thing occurred.
**How to reproduce:**
Change morph and while black changing effects are occurring, right-click on a swet or get close to one. I am unsure if this applies to other mobs that are "rideable".
**Crash log:**N/A

Additional Note: Issue only affects world that issue is reproduced.

**Comment by Lachney** [comment]
Couldn't reproduce this issue with Aether Legacy v3.2 (A new version is also releasing soon) Please reopen t his issue if you are still getting this issue!
