### ISSUE TITLE
Skyroot Buckets Convert to Normal Buckets When Filled By Machines

### ISSUE THREAD

**Issue by Noobulus** [Modding-Legacy/Aether-Legacy#351]
**Aether Legacy Version(s) Affected**:
1.12.2-v3.2

**Forge version**: 
forge-14.23.4.2760

**Extra Mods**: 
ThermalExpansion-1.12.2-5.5.0.29-universal
EnderIO-1.12.2-5.0.33

**Issue:**
Skyroot buckets are transformed to normal buckets whenever they are filled with water in TE and EIO machines.

**How to reproduce:**
Place skyroot bucket in TE Fluid Transposer or EIO Tank with fill mode on and water in the tank and the machine will output a vanilla water bucket.

**Crash log:**

**Comment by 115kino** [comment]
Fixed and tested. New release planned in the coming days.
