### ISSUE TITLE
IC2Classic Compat

### ISSUE THREAD

**Issue by robotbrain** [Modding-Legacy/Aether-Legacy#352]
**Aether Legacy Version(s) Affected**: 1.12.2-v3.2

**Forge version**: 14.23.5.2768

**Extra Mods**: IC2Classic 1.12-1.5.3.8

**Issue:** Crash when using ic2c furnace due to aether adding a recipe with a null item as input

**How to reproduce:** 
With all relevant mods installed, place an ic2c electric furnace and shift-click a copper dust or other smeltable item into the furnace.

**Crash log:**
https://paste.ee/p/ANqhp

See also https://github.com/TinyModularThings/IC2Classic/issues/274

**Comment by 115kino** [comment]
Fixed and tested. New release planned in the coming days.
