### ISSUE TITLE
anything i ride down from the aether disappears

### ISSUE THREAD

**Issue by catbryce** [Modding-Legacy/Aether-Legacy#354]
**Aether Legacy Version(s) Affected**:1.7.10

**Forge version**: 10.13.4.1614

**Extra Mods**:  aether_legacy-1.7.10-v1.0.0 

**Issue:**

**How to reproduce:** ride anything down and it will dissapear

**Crash log:**

**Comment by catbryce** [comment]
sometimes you go under bedrock

**Comment by catbryce** [comment]
you can't ride anything thru aether portals ether

**Comment by KingPhygieBoo** [comment]
This should be fixed in the next update!

**Comment by catbryce** [comment]
the going under bedrock is not fixed

**Comment by KingPhygieBoo** [comment]
How? You can't enter a portal while riding a mob

**Comment by catbryce** [comment]
when you fall out of the aether while riding

**Comment by KingPhygieBoo** [comment]
You should dismount before exiting the Aether

**Comment by catbryce** [comment]
in mid air?

**Comment by KingPhygieBoo** [comment]
Yup, it kicks you off as it falls

**Comment by catbryce** [comment]
that's not how it worked in the original
