### ISSUE TITLE
Extra Features Config (Enhancement)

### ISSUE THREAD

**Issue by KingPhygieBoo** [Modding-Legacy/Aether-Legacy#36]
Add a config option to disable features such as the Orange Moa, and the Phoenix tools. And the Phoenix Sword is also missing.

**Comment by FakenameBill** [comment]
I concur about removing the orange moa. This is supposed to be a modern-Minecraft version of the Aether I after all, and the original Aether didn't have any orange moas. Heck, Aether II doesn't even have orange moas.

**Comment by 115kino** [comment]
Extra features (besides 2) were removed
