### ISSUE TITLE
[Bug] Keeping note of a duplicate stat id

### ISSUE THREAD

**Issue by Lachney** [Modding-Legacy/Aether-Legacy#362]
**Aether Legacy Version(s)**
_Please make sure you are using the latest version for whatever Minecraft version you are using_
aether-legacy-1.7.10-v1.0.0
**Minecraft Version(s) Affected:**
1.7.10
**Extra Mod(s):**
> UCHI    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
    UCHI    CollectiveFrameworkCore{1.0.0-132} [Collective Framework Core] (minecraft.jar)
    UCHI    FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar)
    UCHI    Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar)
    UCHI    AdvancedRocketryCore{1} [Advanced Rocketry] (minecraft.jar)
    UCHI    appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar)
    UCHI    CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar)
    UCHI    ercclasstransform{1.0} [ERCClassTransform] (minecraft.jar)
    UCHI    gasesCore{1.6.7} [Glenn's Gases Core] (minecraft.jar)
    UCHI    gasesFrameworkCore{1.2.4} [Gases Framework Core] (minecraft.jar)
    UCHI    ivtoolkit{1.2.1} [IvToolkit] (minecraft.jar)
    UCHI    LambdaLib|Core{1.2.3} [LambdaLib|Core] (minecraft.jar)
    UCHI    MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks] (minecraft.jar)
    UCHI    NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar)
    UCHI    nvfix{0.0.1} [Night Vision Fix] (minecraft.jar)
    UCHI    OpenComputers|Core{1.7.1.1127} [OpenComputers (Core)] (minecraft.jar)
    UCHI    PlayerAPI{1.4} [Player API] (minecraft.jar)
    UCHI    PotionExtensionCore{1.7.10-1.1.0} [PotionExtensionCore] (minecraft.jar)
    UCHI    modJ_StarMinerCore{0.9.9} [StarMinerCore] (minecraft.jar)
    UCHI    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar)
    UCHI    voltzenginepreloader{0.0.1} [Voltz Engine Preloader] (minecraft.jar)
    UCHI    WitchingGadgetsCore{1.1.10} [Witching Gadgets Core] (minecraft.jar)
    UCHI    OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar)
    UCHI    <CoFH ASM>{000} [CoFH ASM] (minecraft.jar)
    UCHI    <DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar)
    UCHI    mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar)
    UCHI    magneticraftpatcher{1.7.10-0.2} [MagnetiCraft Patcher] (minecraft.jar)
    UCHI    WarpDriveCore{1.7.10-1.4.2.-} [WarpDriveCore] (minecraft.jar)
    UCHI    PeripheralsPlusPlusCore{1.3.6} [Peripherals++ Core] (minecraft.jar)
    UCHI    FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar)
    UCHI    FamiliarsAPI{1.7.10} [Familiars API] (FamiliarsAPI-1.7.10.jar)
    UCHI    gilded-games-util{1.7.10-1.2} [Gilded Games Utility] (gilded-games-util-1.7.10-1.9.jar)
    UCHI    ItemBlacklist{1.2.0.8} [ItemBlacklist] (ItemBlacklist-1.7.10-1.2.0.8.jar)
    UCHI    battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar)
    UCHI    Pistronics2{0.6.3} [Pistronics 2] (1.7.10-Pistronics2-v0.6.4.jar)
    UCHI    securitycraft{v1.8.7} [SecurityCraft] ([1.7.10]+SecurityCraft+v1.8.7.jar)
    UCHI    divinerpg{1.4.1.4} [DivineRPG] ([1.7.10][SMP]DivineRPG-1.4.1.4.jar)
    UCHI    fusionutil{0.1} [FusionUtil] ([1.7.10]FusionUtil-0.1.0.jar)
    UCHI    rpgloot{1.0} [RPG Loot] ([1.7.10]RPGLoot-1.0.7.jar)
    UCHI    CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar)
    UCHI    BuildCraft|Core{7.1.23} [BuildCraft] (buildcraft-7.1.23.jar)
    UCHI    BuildCraft|Transport{7.1.23} [BC Transport] (buildcraft-7.1.23.jar)
    UCHI    BuildCraft|Silicon{7.1.23} [BC Silicon] (buildcraft-7.1.23.jar)
    UCHI    Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar)
    UCHI    WailaAddonBC{1.0.5.1} [WailaAddonBC] ([1.7.10]WailaAddonBC-1.0.5.1.jar)
    UCHI    abyssalcraft{1.9.1.3} [AbyssalCraft] (AbyssalCraft-1.7.10-1.9.1.3-FINAL.jar)
    UCHI    LambdaLib{1.2.3} [LambdaLib] (LambdaLib-1.2.3.jar)
    UCHI    academy-craft{1.0.7} [Academy Craft] (AcademyCraft-1.0.7.jar)
    UCHI    AccidentallyCircumstantialEvents{1.12.11} [Accidentally Circumstantial Events] (accidentallycircumstantialevents-1.12.11.jar) 

**Describe the bug**
Duplicate stat id

**Expected behavior**
it should not have a duplcate stat id 

**Logs**
https://pastebin.com/y8kdAv67

**Additional context**

**Comment by 115kino** [comment]
Issue is fixed in v1.0.1 for Aether Legacy 1.7.10. You can download the latest version [here](https://minecraft.curseforge.com/projects/aether-legacy/files)

**Comment by NonoxSoux** [comment]
@115kino The download is wrong, I downloaded version 1.0.0 instead of 1.0.2, for version 1.7.10
https://minecraft.curseforge.com/projects/aether-legacy/files/2667453 
I have the same mistake ... sorry for reliving an old issue.

**Comment by KingPhygieBoo** [comment]
It is the proper version, just named wrong
