### ISSUE TITLE
moas in 1.7 do not as much health as they shoud

### ISSUE THREAD

**Issue by catbryce** [Modding-Legacy/Aether-Legacy#365]
**Aether Legacy Version(s)**
_Please make sure you are using the latest version for whatever Minecraft version you are using_

**Minecraft Version(s) Affected:**

**Extra Mod(s):**

**Describe the bug**

**Expected behavior**

**Logs/Crash Logs and Screenshots**
If applicable, add crash logs and/or screenshots to help explain your problem.

**Additional context**
that probably means most of the aethers creatures are not right ether

**Comment by 115kino** [comment]
Moa health and certain mob health increased. You can download v1.0.1 for 1.7.10 Minecraft [here](https://minecraft.curseforge.com/projects/aether-legacy/files)
