### ISSUE TITLE
the moas in 1.7 still don't have correct health 

### ISSUE THREAD

**Issue by catbryce** [Modding-Legacy/Aether-Legacy#367]
**Aether Legacy Version(s)**
_Please make sure you are using the latest version for whatever Minecraft version you are using_

**Minecraft Version(s) Affected:**

**Extra Mod(s):**

**Describe the bug**
the moas in 1.7 are still weaker than in 1.12

1.12![image](https://user-images.githubusercontent.com/45723498/50551997-5df41780-0c47-11e9-9812-3177f35ddae8.png)
 1.7
![image](https://user-images.githubusercontent.com/45723498/50552073-fc34ad00-0c48-11e9-8fd4-1fc9215b27c1.png)

**Expected behavior**
moas in 1.7 shoud have as much health as the original

**Logs/Crash Logs and Screenshots**
If applicable, add crash logs and/or screenshots to help explain your problem.

**Additional context**

**Comment by KingPhygieBoo** [comment]
I'm not understanding the issue here, could you be more specific? (also I see you're using my extra moas mod that's pretty cool)

**Comment by catbryce** [comment]
the moas in 1.7 are missing 7 hearts

**Comment by catbryce** [comment]
thank you the pink moas name is Penelope

**Comment by catbryce** [comment]
the moas in 1.7 have 10 hearts. the moas in 1.12 have 17. they should both have 17 hearts like the original is this specific enough

**Comment by Lachney** [comment]
Fixed in next version
