### ISSUE TITLE
Mod incompatibility with The frost Mod

### ISSUE THREAD

**Issue by SpGilbert** [Modding-Legacy/Aether-Legacy#369]
Mod incompatibility at stage 4 of forge launcher

**Aether Legacy Version(s) Affected**:
1.12.2 v3.2
**Forge version**: 
1.12.2-forge1.12.2-14.23.5.2807

**Extra Mods**: 
aether legacy addon (not the problem)
The frost mod (causing the crash when added) vanillafix says Aether legacy is suspected mod.

**Issue:**
crashes at stage 4 out of 7 when loading forge

**How to reproduce:**
just try to load the game

**Crash log:**
https://paste.dimdev.org/culanexipu.mccrash

**Comment by Lachney** [comment]
Hi there!!! So the crash you are getting is a duplicated dimension ID. 
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Aether Legacy (aether_legacy)
Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id 4, One is already registered
```

That means you'll have to change either The Frost Mod or Aether Legacy's Dimension ID.

With Aether Legacy, we have it in a config option. Look in your Minecraft installation's folder and find your config folder, then go inside the aether folder. You could find a config option called AetherI.cfg. Open that up in a text editor like Notepad and change the dimension ID to something that isn't 4.

Here is a wiki page for more information about the configuration file for Aether Legacy
https://github.com/Modding-Legacy/Aether-Legacy/wiki/Configuration

Hope this fixes your issue. Have a lovely day!
