### ISSUE TITLE
Treasure chest in silver dungeon won't spawn

### ISSUE THREAD

**Issue by DeathByTortoise** [Modding-Legacy/Aether-Legacy#375]
**Aether Legacy Version(s)**
v1.0.2
**Minecraft Version(s) Affected:**
1.7.10
**Extra Mod(s):**
alot of them

**Describe the bug**
i yust beat the silver dungeon but i don't get a treasure chest. i do get the silver key

**Expected behavior**
i expected to get an achevment and a chest to spawn like in the brons dungeon

**Comment by Lachney** [comment]
Upon testing this issue, I was able to find the treasure chest. However, can you check this issue is still happening? Feel free to reopen the issue if this is still happening. (Also please do provide your mod list and not "a lot of them") Thank you! :)
