### ISSUE TITLE
alter consumes to much ambrosium 

### ISSUE THREAD

**Issue by catbryce** [Modding-Legacy/Aether-Legacy#385]
**Aether Legacy Version(s)**
_Please make sure you are using the latest version for whatever Minecraft version you are using_

**Minecraft Version(s) Affected:** probably all of them except the original 

**Extra Mod(s):**

**Describe the bug**
A clear and concise description of what the bug is. the alter restores a diamond chest plate in 21 ambrosium 

**Expected behavior**
A clear and concise description of what you expected to happen. originally the alter restored a diamond chest plate in 12 ambrosium 

**Logs/Crash Logs and Screenshots**
If applicable, add crash logs and/or screenshots to help explain your problem.

**Additional context**

**Comment by KingPhygieBoo** [comment]
Here's some things to keep in mind;
Enchanted stuff takes much longer to repair.
You can place Enchanted Gravitite under the Enchanter to speed it up.
