### ISSUE TITLE
[Bug] Gravitite set bonus not granted on latest 1.12.2-v1.4.0

### ISSUE THREAD

**Issue by slyfoxD** [Modding-Legacy/Aether-Legacy#389]
**Minecraft Version(s) Affected:**
1.12.2

**Extra Mod(s):**
OptiFine

**Describe the bug**
I noticed going from mod version 1.12.2-v3.2 to 1.12.2-v1.4.0 the gravitite double jump disappears.   

**Expected behavior**
Before the update it worked fine with a 6 block jump and no fall damage, now I just do a normal jump and still take fall damage.

**Comment by Lachney** [comment]
Just tested this on 1.12.2v1.4.0, I am able to acquire the ability with the full gravitite set. Could you check to make sure that you have the entire set including the gloves? Try equipping and re-equipping the armor. (Maybe like a desync happened for you?)

If you are still getting an issue reply back with Minecraft Forge version you are on (and then test with the  latest recommend version)

**Comment by Lachney** [comment]
Oopsie, I tested this issue in a development build, and can confirm it was an issue in 1.4.0 -- It is fixed in the next update.
