### ISSUE TITLE
Aether Portal doesn't have particles.

### ISSUE THREAD

**Issue by KingPhygieBoo** [Modding-Legacy/Aether-Legacy#39]

**Comment by JAWSAWN** [comment]
And have nether portal sounds instead of the aether portal.

Also the portal frame has no localizations

And portal frama have no moving textures

**Comment by KingPhygieBoo** [comment]
It's supposed to be like that, this isn't Aether II.

**Comment by JAWSAWN** [comment]
Aether 1 had that...

**Comment by TheCorruption** [comment]
Actually, I'm playing aether 1 as we speak and I can confirm that the aether portal didn't have moving textures and made nether portal sounds.

**Comment by 115kino** [comment]
@JAWSAWN There were no portal sounds and there were no moving textures. The only thing that was missing was the localization and the particles which are fixed in v1.3
