### ISSUE TITLE
[Bug] stright up crash

### ISSUE THREAD

**Issue by Nathan22211** [Modding-Legacy/Aether-Legacy#392]
**Aether Legacy Version(s)**
_Please make sure you are using the latest version for whatever Minecraft version you are using_
19w09a 0.0.2

**Minecraft Version(s) Affected:**
19w09a

**Extra Mod(s):**
other than the needed fabric API no other mods

**Describe the bug**
crashes saying it's an unsupported modified version straight up

**Expected behavior**
load the game without a crash

**Logs/Crash Logs and Screenshots**
If applicable, add crash logs and/or screenshots to help explain your problem.
https://pastebin.com/7f8XTHkK

**Additional context**
it crashes without the game loading. (i suspect the .bat files you had in there.)

**Comment by Lachney** [comment]
Hey, noticed you're using Java 10 and I'm not sure if it even works with that. Try Java 8? 😄

**Comment by Nathan22211** [comment]
really wish i knew how to do that on Linux Lachney. and i screwed up what launches .jar files on my windows PC so i can't test if the .bat file is the issue or the java version is.

**Comment by Nathan22211** [comment]
if you want to know one of the errors i got here it is

Error: java.lang.NoClassDefFoundError: sun/reflect/ConstructorAccessor

**Comment by Lachney** [comment]
You can install Java 8 with
`sudo apt install openjdk-8-jre`
