### ISSUE TITLE
sun alter works in the overworld

### ISSUE THREAD

**Issue by catbryce** [Modding-Legacy/Aether-Legacy#396]
**Aether Legacy Version(s)**
_Please make sure you are using the latest version for whatever Minecraft version you are using_

**Minecraft Version(s) Affected:**

**Extra Mod(s):**

**Describe the bug**
A clear and concise description of what the bug is. the sun alter works in the over world

**Expected behavior**
the sun alter should only work in the aether

**Logs/Crash Logs and Screenshots**
If applicable, add crash logs and/or screenshots to help explain your problem.

**Additional context**

**Comment by KingPhygieBoo** [comment]
There's really nothing that can be done about this, the world time is synced over all dimensions.
