### ISSUE TITLE
Snapshot 19W09A- Crashing

### ISSUE THREAD

**Issue by adellacanonica** [Modding-Legacy/Aether-Legacy#397]
**Aether Legacy Version(s) Affected**:

**Forge version**: 

**Extra Mods**:  Got ride of all mods

**Issue:**- Crashing 

**How to reproduce:**- Im going to guess it'
[crash-2019-03-08_21.47.50-client.txt](https://github.com/Modding-Legacy/Aether-Legacy/files/2964347/crash-2019-03-08_21.47.50-client.txt)
s something to do with sponges and being near a underwater monument. 

**Crash log:** Attached

**Comment by Lachney** [comment]
Looks like there is an issue with stone chests in that screenshot? Can you try launching the game with that mod disabled? If it works, then stone chests by itself, and if that works, play around with the mods you have installed to see what could be creating a compatibility issue!
```java.lang.NoClassDefFoundError: net/fabricmc/fabric/block/FabricBlockSettings
	at net.kjmaster.stonechests.block.BlockStoneChest.<init>(BlockStoneChest.java:21)
	at net.kjmaster.stonechests.ModBlocks.init(ModBlocks.java:29)
	at net.kjmaster.stonechests.StoneChests.onInitialize(StoneChests.java:16)```
