### ISSUE TITLE
Nuggets for all metals

### ISSUE THREAD

**Issue by Xorbah** [Modding-Legacy/Aether-Legacy#398]
Topic title. Would like nugget forms for all the metals presented in the Aether. Specifically 1.12.2 and up.

**Comment by KingPhygieBoo** [comment]
Unfortunately we aren't adding any content into the mod, as we want to keep it original. However, if you wanted to, you could make a separate addon for it. Plus, if you keep in mind there are no actual metals in the Aether, so there wouldn't actually be any nuggets anyway
