### ISSUE TITLE
Valkyrie queen stays inside a place where it cant attack you despite being able to teleport.

### ISSUE THREAD

**Issue by TheCorruption** [Modding-Legacy/Aether-Legacy#4]
So if you make a small barrier around the valkyrie queen, you only have to worry about lightning balls, this also works with regular valkyries.
![2016-12-17_15 51 09](https://cloud.githubusercontent.com/assets/22695945/21290204/1336575e-c477-11e6-8e7f-56baff01ee38.png)

**Comment by 115kino** [comment]
Should be fixed in the latest commits and the next version of Aether Legacy. (If not feel free to re-create this issue)
