### ISSUE TITLE
Ambrosium Torches do not give off light

### ISSUE THREAD

**Issue by Lachney** [Modding-Legacy/Aether-Legacy#404]

**Comment by insanj** [comment]
Interested in seeing a fix for this because it's a rather significant part of the early-game in the Aether. Without torches, it's nearly impossible to begin a new world without gathering resources in the vanilla overworld first. Must be a symptom of the new lightning engine in the snapshots.

**Comment by Lachney** [comment]
@insanj It is fixed in the latest release! I forgot to close this issue!
Download it here: https://minecraft.curseforge.com/projects/aether-legacy/files/2689943
