### ISSUE TITLE
(Bug) about spawns etc

### ISSUE THREAD

**Issue by baconbricks** [Modding-Legacy/Aether-Legacy#408]
So no entitys spawn in the aether for me, (Yes i am not on peaceful) also I cant find a single dungeon or anything like it, tired looking for hours, also, once i enter the portal and get there, once I leave it sends me somewhere completley random in the normal world making me run for hours to get back home

**Comment by KingPhygieBoo** [comment]
Do you have any other mods installed?

**Comment by baconbricks** [comment]
No I dont't, The aether is the only mod

**Comment by KingPhygieBoo** [comment]
All I can suggest is to make sure you are on the recommended Forge, I cann't reproduce any of these issues. These images show mobs, and a dungeon, which I found right after entering
![2019-03-31_07 34 51](https://user-images.githubusercontent.com/17862210/55289113-96f77180-5387-11e9-93ae-28d7e3e41be8.png)
![2019-03-31_07 35 17](https://user-images.githubusercontent.com/17862210/55289114-96f77180-5387-11e9-98d0-dc8832f0447a.png)

**Comment by baconbricks** [comment]
Yeah its weird because I don't know at all is causing it.
[image: 2019-03-31_05.45.30.png]
[image: 2019-03-31_05.46.02.png]
