### ISSUE TITLE
[Bug] Golden Oak does not drop Golden Ambers (even with zanite axe)

### ISSUE THREAD

**Issue by NitroBrony** [Modding-Legacy/Aether-Legacy#410]
**Aether Legacy Version(s)**
Latest Version
**Forge Version**
14.23.5.2823
**Minecraft Version(s) Affected:**
1.12.2
**Extra Mod(s):**
CTM, Applied Energistics 2, Biomes O' Plenty, BuildCraft, Code Chicken Lib, ChickenChucks, Chisel, Redstone Flux, CoFH Core, CoFH World, DrZhark's CustomSpawner, ptrmodellib, Decocraft, EnderStorage, EnderCore, Just Enough Items, Thermal Foundation, Thermal Expansion, Ender IO, Mantle, The Twilight Forest, Tinkers Construct, Galacticraft Core, Galacticraft Planets, MJRLengendsLib, Extra Planets, Extra Utilities 2, SonarCore, Flux Networks, ShadowFacts Forgelin, Waila, iChunUtil, TESLA, Tesla Core Lib, Industrial Foregoing, Iron Chest, Mo'Creatures, Modern Lights, Morph, Pam's HarvestCraft, Reforged, Zevac's SurvivalFlight, Thermal Dynamics, ToroHealth Damage Indicator's, Tree Chopper, What are we looking at, Xaero's Minimap

**Describe the bug**
Cleared out an entire gold dungeon island of its golden oak tree's with a zanite axe and I did not receive one golden amber. 

**Expected behavior**
According to PaperBatVG's videos showing off the Aether (he is the one who named all of the Achievements) it is supposed to drop up to 3 or 4 at a time on some logs. Or at least get one when you cut down 5 trees 

**Logs/Crash Logs and Screenshots**
It sounds exactly how it looks

**Additional context**
I'm not sure if this is a massive bug or golden ambers a lot more rare to drop now

**Comment by KingPhygieBoo** [comment]
You need a Gravitite axe

**Comment by NitroBrony** [comment]
https://www.youtube.com/watch?v=QOdh_fINAjU&feature=youtu.be&t=250

**Comment by KingPhygieBoo** [comment]
Oh that's mega old, it doesn't work like that anymore

**Comment by NitroBrony** [comment]
I wish it worked like that lol

**Comment by NitroBrony** [comment]
btw you can not make a furnace with holystone so I can not smelt the gravetite I got

**Comment by KingPhygieBoo** [comment]
There is no furnace, you make an Enchanter and enchant it using that (Not to be confused with the Enchanting Table from vanilla)
