### ISSUE TITLE
[Bug] Crash on Startup "unsupported modified version"

### ISSUE THREAD

**Issue by LokiFrostGiant** [Modding-Legacy/Aether-Legacy#415]
**Aether Legacy Version(s)**
Aether Legacy 1.12.2-v1.4.3

**Forge Version**
Forge 1.12.2-14.23.1.2555

**Minecraft Version(s) Affected:**
I guess it's 1.13.2? I assume 1.12.2 Forge runs 1.12.2 Minecraft (I'm no expert)

**Extra Mod(s):**
Xaero's Minimap & Xaero's World Map addon
Optifine 1.12.2 HD U C6
ToroCraft's Damage indicators

**Describe the bug**
After hitting launch, the forge loading window begins "constructing mods" and etc, then crashes and returns to launcher with message "The game crashed whilst there was a severe problem during mod loading that has caused the game to fail." The full .txt is attached. I tested removing other mods for compatibility issues, but only Aether sparks the crash.

**Expected behavior**
The game not to crash before completing loading.

**Logs/Crash Logs and Screenshots**

[crash-2019-04-15_13.51.14-client.txt](https://github.com/Modding-Legacy/Aether-Legacy/files/3081671/crash-2019-04-15_13.51.14-client.txt)

**Comment by KingPhygieBoo** [comment]
I suggest updating Forge to the recommended, it's very out of date. I also suggest updating to Aether Legacy v1.4.4. See if it still happens then

**Comment by LokiFrostGiant** [comment]
I downloaded the newer recommended forge, and the game started up. yet on creating a new world I was given this new crash error.
[crash-2019-04-15_16.24.18-server.txt](https://github.com/Modding-Legacy/Aether-Legacy/files/3082133/crash-2019-04-15_16.24.18-server.txt)

**Comment by LokiFrostGiant** [comment]
Also when trying to open a previous world I crash again with the message "The game crashed whilst exception ticking world." Should I open a new issue since I've passed the barrier of the original?

**Comment by KingPhygieBoo** [comment]
That last crash doesn't seem to involve Aether at all by the looks of it 😦

**Comment by LokiFrostGiant** [comment]
Yeaahh after getting all of it working, found out I need to update my Optifine for Shaders. Been a bit since I’ve played so I’m a little off my game lol thanks for all the help. Aether isn’t causing me any issues now though :P
