### ISSUE TITLE
Pro tip disable option doesn't work.

### ISSUE THREAD

**Issue by OktayYeniTR** [Modding-Legacy/Aether-Legacy#416]

**Comment by KingPhygieBoo** [comment]
Yes actually! It can be disabled in the config.

**Comment by OktayYeniTR** [comment]
visual_options {
        # Disables the random trivia/tips you see during loading screens
        B:trivia_disabled=false
    }


i disabled but it isn't work

**Comment by KingPhygieBoo** [comment]
Alrighty, then I will get this fixed next update.

**Comment by Lachney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Pro tip disable option doesn't work.](https://trello.com/c/ZxPfsq5O/12-pro-tip-disable-option-doesnt-work)

**Comment by KingPhygieBoo** [comment]
I just realized, you have trivia_disabled set to false, it needs to be true to disable it. I tested this, and it works properly.
