### ISSUE TITLE
[Suggestion/Enhancement] Add config to have altar instead of enchanter

### ISSUE THREAD

**Issue by JAWSAWN** [Modding-Legacy/Aether-Legacy#43]
I'd love to see those floating enchanter coming back. It was still on the aether 1 but on the later updates. It was much more interesting to craft with floating ambrosium.

Also add  jei support which I assume soon to come.

**Comment by FakenameBill** [comment]
The floating-ambrosium-altar was not added until the first release of Aether II, I believe. The name was changed to Altar as soon as enchanting tables were added to the vanilla game though

**Comment by 115kino** [comment]
The Altar was added in Aether II. The name Altar was given to the enchanter for reasons still unexplained. JEI support will be added but as a separate mod.
