### ISSUE TITLE
[Suggestion] Add Baubles support when detected.

### ISSUE THREAD

**Issue by JAWSAWN** [Modding-Legacy/Aether-Legacy#44]
Just move the aether accessories to baubles area, Remove the baubles crafting bench and put the accessories slot there instead.

So main inventory screen looks the same.

**Comment by Zygus42** [comment]
Just removed this mod from our build due to this issue.  It was either this or Baubles - was unplayable with both due to the changes to the inventory GUI, and we didn't want to lose Botania which relies on Baubles.  Shame, looked like an interesting mod.

**Comment by 115kino** [comment]
There are too many inventory mods to keep track so i'm making separate inventory compatibility mods so people can choose what inventory should be supported

**Comment by Swerving** [comment]
Is the bauble compatibility mod still going to be a thing? Having two equipment inventories at once seems unbalanced, The equippable items could be re-purposed into baubles,

Capes & Gloves = Chest Slot
Shield & Trinkets = Charm Slot
