### ISSUE TITLE
Sun Spirit Enhancements

### ISSUE THREAD

**Issue by KingPhygieBoo** [Modding-Legacy/Aether-Legacy#46]
Make the hands move around slightly like the player's, as well as make the Sun Spirit look at you when you talk to it.

**Comment by TheCorruption** [comment]
Also, the Sun spirit and Valkyrie queen don't really feel like they're "alive", they just stand still unlike aether 1 where they would look around and sometimes at you, and the Valkyrie queen would walk around and jump and teleport occasionally

**Comment by 115kino** [comment]
Sun Spirit movement added back and Valkyrie battle heavily modified in v1.4
