### ISSUE TITLE
Aerclouds arent colored correctly

### ISSUE THREAD

**Issue by TheCorruption** [Modding-Legacy/Aether-Legacy#52]
Top is aether 1, bottom is aether legacy.
![2017-01-11_13 58 56](https://cloud.githubusercontent.com/assets/22695945/21864613/2eb63a0e-d808-11e6-9a7d-0e4bdabfc4af.png)

![2017-01-11_13 59 05](https://cloud.githubusercontent.com/assets/22695945/21864337/f0df8f9c-d806-11e6-8ce7-05458d13d2a7.png)

**Comment by TheCorruption** [comment]
Also, in the aether 1 the aerclouds had shadows, but in aether legacy they're completely transparent, they looked better IMO. 
![2017-01-17_17 48 25](https://cloud.githubusercontent.com/assets/22695945/22045688/5ba7796e-dce1-11e6-931d-9b88095ee985.png)

**Comment by 115kino** [comment]
Fixed in v1.3 however the lighting cannot be fixed. I cannot change transparency
