### ISSUE TITLE
The slider's eye doesnt glow in the dark

### ISSUE THREAD

**Issue by TheCorruption** [Modding-Legacy/Aether-Legacy#53]
But in the aether 1, it does, top is aether 1, bottom is aether legacy.

![2017-01-11_13 42 50](https://cloud.githubusercontent.com/assets/22695945/21864955/96bdec2c-d809-11e6-93af-3df112630e82.png)
![2017-01-11_14 23 33](https://cloud.githubusercontent.com/assets/22695945/21864957/992769fc-d809-11e6-90dd-96cb66ecafa5.png)

**Comment by 115kino** [comment]
Fixed in v1.3
