### ISSUE TITLE
The sky is blue

### ISSUE THREAD

**Issue by TheCorruption** [Modding-Legacy/Aether-Legacy#54]
It should be lavender blue, the top is Aether 1, the bottom is Aether Legacy.
![2017-01-11_14 10 14](https://cloud.githubusercontent.com/assets/22695945/21865124/60737654-d80a-11e6-9b06-a245e16e454a.png)
![2017-01-11_14 31 33](https://cloud.githubusercontent.com/assets/22695945/21865199/b76b1822-d80a-11e6-9bd6-90c1c798b627.png)

**Comment by 115kino** [comment]
Note to self: Sky is lavander blue not blue

Anyways, fixed in v1.3
