### ISSUE TITLE
Major Request - Hotkey To Modded GUI 1.10.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Modding-Legacy/Aether-Legacy#56]
Love the mod hate the forced GUI can you please make it; its own thing? preferably set to its own container? I don't want my vanilla GUI modded; that is why I respect mods like Cosmetic armor and over-powered inventory so much.

**Comment by 115kino** [comment]
Same as #44 which I will make different mods for inventory compatibility.

**Comment by P3rf3ctXZer0** [comment]
@115kino has this been fixed
