### ISSUE TITLE
Hammer of Notch crashes server when used

### ISSUE THREAD

**Issue by SansIsTyping** [Modding-Legacy/Aether-Legacy#6]
This made Kino's server crash. You're welcome Bailey.

**Comment by TheCorruption** [comment]
It seems to crash when It lands on a block, also it crashes on singleplayer.

**Comment by EnderT5** [comment]
Same crash happens to me:
https://gist.github.com/anonymous/75a33a89600a13c694462321abe2643c

**Comment by 115kino** [comment]
Fixed in latest commits.
