### ISSUE TITLE
Gravitite Tools doesn't levitate mobs or blocks when right clicked

### ISSUE THREAD

**Issue by JAWSAWN** [Modding-Legacy/Aether-Legacy#60]
I know tools are supposed to levitate their responding blocks like pick -> stone,ores
sword -> mobs

**Comment by 115kino** [comment]
The tool issue is confirmed to be broken (which i'm working on fixing right now)
Only the sword is supposed to levitate mobs and I cannot seem to find an issue with it.

**Comment by 115kino** [comment]
Gravitite tools fixed in v1.3
