### ISSUE TITLE
Aether Legacy is incompatible with Liteloader

### ISSUE THREAD

**Issue by LoganPaul1** [Modding-Legacy/Aether-Legacy#61]
Every time I attempt to load Aether Legacy with Liteloader installed alongside Forge, It crashes when I try to load into a world.

[Crash Report.txt](https://github.com/Modding-Legacy/Aether-Legacy/files/706328/Crash.Report.txt)

**Comment by 115kino** [comment]
This doesn't look like this involves aether legacy. Please reinstall Lightloader and Forge and see if you come across any issues. (If you do you can re-create this issue)
