### ISSUE TITLE
Day/Night cycle

### ISSUE THREAD

**Issue by FakenameBill** [Modding-Legacy/Aether-Legacy#62]
There is a day and night cycle in the Aether. In the original Aether, it never got completely dark before conquering a gold dungeon. I checked some old versions, and in the Beta 1.7.3 version it got dim enough for cockatrices to spawn, and in the 1.2.5 version the sun never moved from the top of the sky.

**Comment by jorgeiscool2** [comment]
Issues with the day night cycle in Aether Legacy is server side, same reason we didn't add the Sun Totem thing to change time. It's possible yes but doing it is unlikely~

**Comment by 115kino** [comment]
The day and night cycle will continue to be in Aether Legacy for the sake of multiplayer.

**Comment by FakenameBill** [comment]
If the day and night cycle can't be removed, is there any way to make it stay light at night? Or is that server side as well?

**Comment by TheCorruption** [comment]
The only way to remove it is possibly /gamerule DoDaylightCycle false

**Comment by catbryce** [comment]
so i think the problem is that if more than one person has the sun alter they wood end up fighting for control
