### ISSUE TITLE
Texts such as "Building Terrain" are missing.

### ISSUE THREAD

**Issue by KingPhygieBoo** [Modding-Legacy/Aether-Legacy#70]

**Comment by DeGariless** [comment]
What happened to this issue? I would like to request that there be a config option to bring back the "building terrain"

**Comment by 115kino** [comment]
I think it was one of those issues I haven't quite looked at however it's been fixed at the beginning of 1.4's development

**Comment by DeGariless** [comment]
Great. Thank you for the clarification. :)
