### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by KingPhygieBoo** [Modding-Legacy/Aether-Legacy#71]
Skyroot Logs do not drop, unless broken with a Skyroot Axe, which then it drops one log, or broken by a Gravitite Axe, where it drops 1 Golden Amber and one Skyroot Log, the same applies to Golden Oak.
TNT Can also make Golden Oak Logs drop themselves.

**Comment by 115kino** [comment]
Fixed all metadata issues with double dropped blocks in v1.3
