### ISSUE TITLE
Golden Oak trees when grown with bonemeal, have invisible leaves

### ISSUE THREAD

**Issue by BiwaShiwaBiwa** [Modding-Legacy/Aether-Legacy#76]
They spawn naturally with leaves, but when manually grown the leaves are invisible.  Golden Oaks also do not drop golden orbs using any type of Aether axe and drop far too many saplings.

![2017-01-30_11 53 51](https://cloud.githubusercontent.com/assets/11281305/22422149/d1ecb93a-e6e2-11e6-92f9-50b2ebe287b7.png)

Update:  Closing the world and loading it back up makes the leaves visible.

**Comment by 115kino** [comment]
Fixed in v1.4
