### ISSUE TITLE
Crash with Shaders (OptiFine)

### ISSUE THREAD

**Issue by InsomniaKitten** [Modding-Legacy/Aether-Legacy#77]
Game crashes when opening inventory to the Aether Legacy accessories GUI with a shaderpack enabled. This seems to occur when you enable a shader pack whilst the world is loaded.

**Mod version:** [1.3.1](https://minecraft.curseforge.com/projects/aether-legacy/files/2372455)
**Forge version:** [1.10.2-12.18.3.2221](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.10.2-12.18.3.2221/forge-1.10.2-12.18.3.2221-changelog.txt)
**OptiFine version:** [1.10.2_HD_U_D6](http://optifine.net/changelog?f=OptiFine_1.10.2_HD_U_D6.jar)

**Crash report:** [crash-2017-02-09_16.20.26-client.txt](https://gist.github.com/a90f06da87dc8a5c844f4388406ebe0c)

**Comment by 115kino** [comment]
Which Shader pack are you using? I've used the SUES Ultra Motion Blur, SUES Ultra and Internal shaders and none have crashed the client.
