### ISSUE TITLE
Cannot Pickup Modded Fluids

### ISSUE THREAD

**Issue by InsomniaKitten** [Modding-Legacy/Aether-Legacy#79]
Trying to pick up modded fluids with an empty vanilla bucket results in a bucket of lava or a bucket of water.

**Aether Legacy version:** [1.3.1](https://minecraft.curseforge.com/projects/aether-legacy/files/2372455)
**Forge version:** [1.10.2-12.18.3.2221](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.10.2-12.18.3.2221/forge-1.10.2-12.18.3.2221-changelog.txt)

**Comment by 115kino** [comment]
Does this happen without Aether Legacy?

**Comment by InsomniaKitten** [comment]
I can pick up modded fluids perfectly fine without Aether Legacy in the instance.

**Comment by Natey214** [comment]
Having the same problem, a minor issue with most mods but some a pretty major one.

**Comment by 115kino** [comment]
Should be fixed in 1.4 however i'll leave this open due to uncertainty

**Comment by 115kino** [comment]
Tested with other mods, works fine with v1.4

**Comment by Natey214** [comment]
Fantastic! Any ETA on 1.4?

**Comment by 115kino** [comment]
Shooting for tonight or tomorrow!
