### ISSUE TITLE
Slider can get stuck easily

### ISSUE THREAD

**Issue by TheCorruption** [Modding-Legacy/Aether-Legacy#8]
If you're on the other side of the Chest area, the slider will stop and wont slide up to attack you.
![2016-12-18_12 03 57](https://cloud.githubusercontent.com/assets/22695945/21295414/5d7ca5cc-c51a-11e6-98cb-1515ba258597.png)

**Comment by TheCorruption** [comment]
In 1.3, this still isn't fixed, I think the issue should be reopened.

**Comment by KingPhygieBoo** [comment]
You can also place any Dungeon blocks around him, you don't even need to move him at all.
