### ISSUE TITLE
Aether's log

### ISSUE THREAD

**Issue by BlueStoneW** [Modding-Legacy/Aether-Legacy#80]
The Aether Logs does not point at the position where the player puts it. And the skyroot log have the golden oak log texture.
![2017-02-17_10 37 46](https://cloud.githubusercontent.com/assets/25844310/23066334/2d59c2a0-f501-11e6-9edd-410107823f67.png)

**Comment by 115kino** [comment]
Going straight to work on that

**Comment by 115kino** [comment]
Skyroot and Golden Oak logs now rotate in 1.4 (be prepared to backup worlds)
