### ISSUE TITLE
The book of lore has overlapping text when empty

### ISSUE THREAD

**Issue by TheCorruption** [Modding-Legacy/Aether-Legacy#91]
Not sure what exactly happened, but an empty slot gives this entry.
![2017-03-22_07 56 10](https://cloud.githubusercontent.com/assets/22695945/24198777/40cdb1c8-0ed5-11e7-99fa-82a6a2759f28.png)

**Comment by 115kino** [comment]
What Minecraft versions does this effect?

**Comment by TheCorruption** [comment]
1.11, I'm also using JEI and Neat, I don't think it makes a difference though.

**Comment by 115kino** [comment]
No it does not, its fixed in v1.4.1 (will release asap)
