### ISSUE TITLE
Quick load sets your gamemode as survival

### ISSUE THREAD

**Issue by TheCorruption** [Modding-Legacy/Aether-Legacy#92]
If you made a creative world, then went back to the title screen, clicking "quick load" will change your gamemode to survival.

**Comment by 115kino** [comment]
Yes, the Aether menu is only meant for survival worlds. The switching of game modes isn't reliable using the worlds instance of the game type so the Quick load is strictly kept to survival. (Hence the deletion of Quick Load deleted in Aether 1.2.5)
