### ISSUE TITLE
[1.11.2][1.4.0] Config for the custom main menu is inverted

### ISSUE THREAD

**Issue by starg09** [Modding-Legacy/Aether-Legacy#94]
So, this is how it generated originally, after adding the mod to our pack:

```
"aether menu options" {
    B:"Use Aether Menu"=false
}
```

However, the menu was there. Once I changed that to `true`, and restarted the game, was the menu gone.

So it might be a good idea to either rename it to "Disable Aether Menu", or make it true by default and inverting how it works 😛

**Comment by 115kino** [comment]
Fixed the "inverted" issue in v1.4.1 (will release asap)
