### ISSUE TITLE
[1.11.2][1.4.0][Suggestion] Add support for chiseled glowstone

### ISSUE THREAD

**Issue by starg09** [Modding-Legacy/Aether-Legacy#95]
This is pretty minor, but since this mod is used in most packs it could be a nice synergy. Currently portals can only be made with vanilla glowstone, and one from other mods doesn't work. Chisel adds many variations for the block, which could look nicely for a portal inside someone's base. Adding compatibility to those would most likely improve the overall experience, I think :)

**Comment by brodycas3** [comment]
Or you can use forge microblocks and cover it with panels

**Comment by starg09** [comment]
Well, not every person playing will have microblocks or MCMP installed, but may have Chisel. Making an integration like this depend on a third, unrelated mod wouldn't make much sense...

**Comment by KingPhygieBoo** [comment]
This is not going to be added, mod compatibility isn't a high priority at this time, this issue will be reopened when it's time to work on that. 😄

**Comment by brodycas3** [comment]
Instead of closing it you should make a backlog tag to add to issues like
this, just a friendly suggestion
