### ISSUE TITLE
[1.10.2] Joining a sp world for the first time causes an aether title screen to show up

### ISSUE THREAD

**Issue by JAWSAWN** [Modding-Legacy/Aether-Legacy#96]
So I jave created a new world with the latest aether ver and made a new world. FYI aether menu is disabled in the configs.
Then after I opened it and there was an aether main menu screen. Which i pressed single player and opened a gane from it which ended up never working and i had to shut it down.

But pressing esc loads the world as normal and upon re opening the world it doesnt pop up.

**Comment by 115kino** [comment]
Aether menu removed for v1.4.1 (will release asap)
