### ISSUE TITLE
[1.10.2] Minecraft music plays in the Aether and gets combined with it

### ISSUE THREAD

**Issue by JAWSAWN** [Modding-Legacy/Aether-Legacy#97]
In the aether (survival) after aether music starts playing the minecraft overworld music also starts to play which turns into an ugly cacophony. Mute minecraft music.

**Comment by JAWSAWN** [comment]
Actually aether music plays regardless minecraft music settings are turned off.

**Comment by 115kino** [comment]
Fixed in v1.4.1 (will release asap)
