### ISSUE TITLE
[1.10.2] Updating server to 1.4 from 1.3.1 crash / even with a fresh world save

### ISSUE THREAD

**Issue by JAWSAWN** [Modding-Legacy/Aether-Legacy#98]
https://gist.github.com/JAWSAWN/7476571ea200e3e16565df4e3be6aae1

**Comment by JAWSAWN** [comment]
So I made a new world in multiplayer and it still didnt boot up.
https://gist.github.com/JAWSAWN/d53397012291cce9154b4a2377823d95

**Comment by 115kino** [comment]
It'a due to the proxy location not being updated from the cleanup. Its fixed in v1.4.1 on all versions (will release asap)
