### ISSUE TITLE
[1.11.2] Minecraft automatically loads saved world as Aether 

### ISSUE THREAD

**Issue by blackviperr** [Modding-Legacy/Aether-Legacy#99]
forge loads successfully but minecraft completely bypasses its main menu & loads a random save, which actually loads the Aether I menu (w music).. The Aether menu config is automatically set to false, but it still happens anyways. 9/10 game will freeze w lonely dirt background forever ,,,,

http://pastebin.com/a7CDCdQB

**Comment by DeGariless** [comment]
Temporary fix. Set "Use Aether Menu" to true
https://github.com/Modding-Legacy/Aether-Legacy/issues/94

**Comment by blackviperr** [comment]
thank you xo

**Comment by 115kino** [comment]
Aether menu removed for v1.4.1 (will release asap)
